/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "- (Required:": "- (要求:",
    "- spending": "- 花费",
    "= net per day)": "= 每天净收入)",
    "/day": "/天",
    "Work": "工作",
    "Beggar": "乞丐",
    ") * level * charisma * job multiplier * specific multipliers": ") *等级*魅力*工作乘数*具体乘数",
    "Age:": "年龄:",
    "base revenue (": "基本收入(",
    "Basic jobs": "基础工作",
    "beta version :": "测试版:",
    "Character": "角色",
    "Current Job:": "当前工作:",
    "Cyberpunk Life": "赛博朋克生活",
    "Day:": "天数:",
    "Events": "事件",
    "Exp": "经验值",
    "Focus:": "专注:",
    "Game loaded": "游戏已加载",
    "Gym access": "健身房访问权限",
    "Hey! Come here, you may find": "嘿!到这儿来，你会发现",
    "income": "收入",
    "Income /day:": "收入/天:",
    "Income/day": "收入/天",
    "Inventory": "库存",
    "Key to the renting system": "租赁系统的关键",
    "Level": "等级",
    "level :": "等级:",
    "level max :": "最高等级:",
    "MaxLevel": "最高等级",
    "Money": "金钱",
    "Money Total:": "总计金钱:",
    "NaN": "NaN",
    "Next unlock:": "下一个解锁:",
    "NextLevel": "下一级",
    "Open / close": "打开/关闭",
    "OPTIONS": "选项",
    "PAUSE": "暂停",
    "Press delete to remove it and escape to cancel.": "按delete键删除，escape键取消",
    "Press enter or space to select a node.": "按“enter”或“空格”选择节点。",
    "Press enter or space to select an edge. You can then press delete to remove it or escape to cancel.": "按回车键或空格键选择一条边。然后，您可以按delete键删除它，或按escape键取消它。",
    "React Flow mini map": "反应流迷你地图",
    "Shop": "商店",
    "something useful...": "有用的东西…",
    "Story -": "剧情 -",
    "The game has been loaded 👌": "游戏已经加载👌",
    "XP /day:": "经验 /天:",
    "You can then use the arrow keys to move the node around.": "然后可以使用箭头键移动节点。",
    "You get orders from an app, then have to do everything asked. Faster than this if you want to keep a good rating.": "你从应用程序获得订单，然后必须完成所有要求。如果你想保持良好的评级，速度要比这个快。",
    "You wander in the streets...": "你在街上游荡……",
    "In the sterile, neon-lit corridors of the state's child-producing facility, you come into existence. Strangely, the processus of insemination took 0.8 seconds more than expected. The machinery hums, a line reporting the anomaly appears somewhere on a server log, and you are cast into the sprawling, brutalist cityscape, barely more than your ID number.": "在这个国·家的生育机构里，你在无菌的、霓虹灯照亮的走廊里诞生了。奇怪的是，授精过程比预期多花了0.8秒。机器嗡嗡作响，服务器日志上某处出现了一条报告异常的行，你被扔进了杂乱无章的野兽派城市景观中，只比你的身份证号码多一点点。",
    "Released from the state’s cold embrace, you find yourself adrift in a metropolis where survival is a bitter struggle. As a beggar, the streets become your harsh tutors, teaching lessons of endurance amidst the relentless rain and flickering advertisements. Each day is a battle against hunger and despair, with progress a distant glimmer on the horizon.": "从这个国·家冰冷的怀抱中解脱出来，你发现自己在一个大都市中漂泊，在那里生存是一种痛苦的挣扎。作为一个乞丐，街道成为你苛刻的导师，在无情的雨和闪烁的广告中教导你忍耐。每一天都是一场与饥饿和绝望的战斗，进步的曙光在地平线上隐约可见。",
    "Base money :": "基础金钱:",
    "Birth": "出生",
    "Condition": "条件",
    "Down and Out in Paris and London": "巴黎伦敦落魄记",
    "It's not like you have a choice": "你又没有选择的余地",
    "Money panel": "金钱面板",
    "See the balance between income and spending, and the current total of your money.": "查看收入和支出之间的余额，以及当前的资金总额。",
    "You are born": "你出生了",
    "You are poor and have no resources.": "你很穷，没有资源。",
    "You started the game": "你开始了游戏",
    "Price :": "价格 :",
    "Messages": "消息",
    "A Cog in the Machine": "机器上的一个齿轮",
    "A dilapidated abode, where pests are the landlords. It leaks when it rains, but it is home.": "破败的住所，害虫是房东。下雨时漏水，但这是家。",
    "A new item is available in the shop": "商店里有一种新产品",
    "Add a (negative) multiplier to expenses": "在费用上加一个(负)乘数",
    "Add a multiplier to skill XP": "为技能经验增加一个乘数",
    "Add a multiplier to work XP": "为工作经验增加一个乘数",
    "An outdated laptop with rusty edges, yet still capable of performing basic tasks.": "一台边缘生锈的过时笔记本电脑，但仍能执行基本任务。",
    "Base cost:": "基本费用:",
    "Capsule": "胶囊",
    "Charisma": "魅力",
    "Close All": "全部关闭",
    "Cost per day:": "每日费用:",
    "Effect:": "效果:",
    "Enhance your cognitive abilities, making you a better problem-solver and thus improving your efficiency at work.": "增强你的认知能力，使你成为一个更好的问题解决者，从而提高你的工作效率。",
    "Flat-sharing with a drug addict": "和一个瘾君子合租",
    "Focus": "专注",
    "Frugality": "节俭",
    "Gear": "装备",
    "Gear Renting System": "设备租赁系统",
    "General skills": "基本技能",
    "Home": "家",
    "Home Renting System": "房屋租赁系统",
    "Homeless": "无家可归的人",
    "Homes": "房屋",
    "In a dark kitchen, you cook a new, AI created menu every day. Strangely, that AI really pushes octopus sandwiches.": "在黑暗的厨房里，你每天都要做一份人工智能创建的新菜单。奇怪的是，这个人工智能真的推出了章鱼三明治。",
    "Is active": "已开启",
    "Life in here is hell, but you have a roof over the head.": "这里的生活是地狱，但你有个栖身之所。",
    "Master the art of making the most of resources. A crucial skill for someone who started with nothing.": "掌握充分利用资源的艺术。对于白手起家的人来说，这是一项至关重要的技能。",
    "Max : last 500 seconds": "最大：最近500秒",
    "Money chart": "金钱图表",
    "Multiply focus by:": "专注乘以:",
    "Old laptop": "旧笔记本电脑",
    "Old Motel Room": "旧汽车旅馆房间",
    "Pills subscription": "药丸订购",
    "Scratch card game": "刮刮卡游戏",
    "Shop alert": "商店提示",
    "Skill training": "技能培训",
    "Skills": "技能",
    "Slum Shack": "贫民窟的小屋",
    "Tablet": "平板电脑",
    "The ability to find inner peace boosts your capacity to learn.": "找到内心平静的能力可以提升你的学习能力。",
    "The screen is cracked and it is really old.": "屏幕裂了，而且很旧。",
    "Training:": "训练:",
    "Virus scripts": "病毒脚本",
    "With this you can see your money history in real time.": "有了这个，你可以实时看到你的钱的历史。",
    "x(multiplier) basic jobs XP": "x(乘数)基础工作经验",
    "x(multiplier) skill XP": "x(乘数)技能经验",
    "XP/day": "经验/天",
    "You can only sleep here.": "你只能睡在这里。",
    "You have your first paying job": "你有了第一份有报酬的工作",
    "You need this to be able to rent a home, or equipment. Incredible that you don't already have it.": "你需要这个才能租房子或设备。难以置信你居然还没有。",
    "You will be able to train on some skills.": "你将能够训练一些技能。",
    "You will get a scratch card game regularly.": "你会定期得到一个刮刮卡游戏。",
    "You will receive pills regularly. You have to seize the opportunity when it's here.": "你会定期收到药片。当机会来临时，你必须抓住它。",
    "Security agent by night": "夜间安保人员",
    "You do the same task all day.": "你整天都在做同样的工作。",
    "Reincarnate": "转生",
    "You are dead.": "你老死了。",
    "You start feeling really old.": "你开始觉得自己真的老了。",
    "You will probably be dead in a year 😱": "你可能会在一年内死去😱",
    "Click here to start a new life.": "点击这里开始新的生活。",
    "You will be 20 years old again, you will lose everything except the shop and clinic objects unlocked, and gain an important bonus : the max level in jobs and skills will be saved and will make it easier to level up.": "你将再次回到20岁，你将失去一切，除了商店和诊所对象解锁，并获得一个重要的奖励:工作和技能的最高等级将被保存，并将使其更容易升级。",
    "After seven decades of life’s virtual reality simulation, your journey ends with a standard-issue expiration notice. The state’s bureaucracy ensures that your final moments are as uneventful as a power outage. You reflect on a life of mundane compliance, your heart ceasing its beats in perfect bureaucratic rhythm. The city is of course indifferent to your departure.": "经过70年的虚拟现实模拟生活，你的旅程以一份标准的到期通知结束。国·家的官·僚机构确保你的最后时刻像停电一样平安无事。你反思着平凡顺从的生活，你的心脏在完美的官僚节奏中停止跳动。这座城市当然不会在意你的离去。",
    "Congratulations! You’ve landed your first paying job, working for an app that micromanages every breath you take. All day, your chip chirps instructions into your ear: walk, talk, deliver, type, repeat. Every action is timed to the second, and rated. It’s hard, sure, but at least you’re no longer dining exclusively on dumpster cuisine.": "恭喜你!你已经找到了你的第一份有偿工作，为一款微管理你每一次呼吸的应用程序工作。你的芯片整天在你耳边唧唧喳喳地发出指令:走路、说话、传递、打字、重复。每个动作都是计时到秒的，并进行评级。当然，这很难，但至少你不用再只吃垃圾桶里的菜了。",
    "(this loop:": "(当前循环:",
    ") can be used to unlock important objects in the clinic.": ")可以用来解锁诊所里的重要物品。",
    "⇾ Karma total :": "⇾业力总计:",
    "A computer glitches during an insemination. And seemingly that's all it takes, you’re reborn, carrying echoes of past skills and experiences. Nobody understands why you're obsessed with déjà vu...": "在人工授精过程中，电脑出现故障。似乎这就是一切，你重生了，带着过去的技能和经验的回声。没有人理解你为什么痴迷于 gityx.com...",
    "Clocking Out": "打卡",
    "Karma (": "业力 (",
    "Karma after transfer :": "转让后的因果报应:",
    "Karma panel": "业力面板",
    "Karma per day = ((money per day / 10) + (PI per day / 100) + NI total) / 100 000 000": "每天的业力 = ((每天的钱 / 10) + (每天的PI / 100) + NI 总数) / 100 000 000",
    "Karma this loop :": "当前循环业力:",
    "Karma:": "业力:",
    "Reboot": "重启",
    "You died": "你死了",
    "You gain karma daily, but you'll be able to use it only after a reincarnation (it will then be transfered in the total).": "你每天都会获得业力，但你只有在转生之后才能使用它(然后它会被转移到总数中)。",
    "You have the opportunity to live your life again": "你有机会重新开始你的生活",
    "Karma.": "业力.",
    "Add a multiplier to work revenue": "增加工作收入的乘数",
    "but I already have you in the client DB...": "但我已经在客户数据库里找到你了",
    "Clinic access": "诊所访问权限",
    "It's weird, I'm sure we never met,": "很奇怪，我们肯定没见过面，",
    "Street Cred": "街头信条",
    "The stains on the walls and carpet tell a thousand tales. Not the best, but private.": "墙上和地毯上的污迹诉说着千言万语。不是最好的，但很私密。",
    "This will allow you to enter the Clinic.": "这能让你进入诊所。",
    "Underground Bunker": "地下室",
    "You are dead. If you reincarnate now, you will get": "你已经死了。如果你现在转世，你会得到",
    "Your charisma allows you to influence others with ease, proving beneficial in work situations and increasing your revenue.": "你的魅力使你能轻松地影响他人，在工作中证明自己是有益的，并增加你的收入。",
    "Enable Autosave (will save the game every 5 seconds).": "开启自动保存(每5秒保存一次游戏)。",
    "Game changelog here": "这里是游戏更新日志",
    "Join the Discord Server:": "加入Discord服务器:",
    "Load Game": "加载游戏",
    "Reset Game (delete save!)": "重置游戏(删除存档!)",
    "Save Game": "保存游戏",
    "Body modifications": "身体装饰",
    "Buy objects with money. You will keep them after a reincarnation.": "用金钱购买物品。转生后可保留",
    "Character panel": "角色面板",
    "Choose a job and monitor your experience progress here.": "在这里选择一份工作，并监控你的经验进步。",
    "Choose a job to earn money and gather experience in that role. As you progress, you'll advance in levels.": "选择一份既能赚钱又能积累经验的工作。随着你的进步，你的等级也会提高。",
    "Do you have siblings in": "你有兄弟姐妹在",
    "Each level up increases your pay and opens up opportunities for new jobs.": "每升一级都会增加你的收入，并为你提供新的工作机会。",
    "Elevate it by renting better homes and gear.": "通过租用更好的房子和设备来提升它。",
    "Events panel": "事件面板",
    "Focus enhances your skill and job experience gain. Your current focus level is:": "专注可以提高你的技能和工作经验。你当前的专注等级:",
    "Get access to a new menu in the clinic.": "获得诊所新菜单的权限。",
    "Here in Ubik Group™ we're delighted to have you as a renter. Adjust your home and equipment depending on your revenue!": "在 阳光帝国，我们很高兴您成为我们的租客。根据你的收入调整你的家和设备!",
    "Here you can rent a home to upgrade your Focus.": "在这里，你可以租用房屋来升级你的专注。",
    "Home panel": "家面板",
    "Key details about your character are displayed here.": "关于你的角色的关键细节在这里显示。",
    "Select a skill to make it progress.": "选择一个技能，使其进步。",
    "Shop panel": "商店面板",
    "Skills have various effects like adding multipliers to jobs xp or revenue, decreasing expenses etc.": "技能有各种各样的效果，比如增加工作经验或收入的乘数，减少开支等。",
    "Skills panel": "技能面板",
    "the area or something ?": "这片区域还是什么?",
    "The learning speed depends on Focus.": "学习速度取决于专注。",
    "Work panel": "工作面板",
    "years.": "年。",
    "You begin the game at the age of": "你开始游戏的年龄是",
    "You can also equip or unequip different gear, each one has a specific effect.": "你也可以装备或不装备不同的装备，每一个都有特定的效果。",
    "You can rent for a cost superior to your revenue, if your money falls to 0 you'll be homeless again and every gear will be unequiped.": "你可以以高于收入的价格租房，如果你的钱降至0，你将再次无家可归，一切都将毫无疑问。",
    "Your expected lifespan is:": "你的预期寿命是:",
    ") to unlock important upgrades": ")来解锁重要的升级",
    "A collection of scripts used to steal money.": "用来偷钱的脚本集合。",
    "A compact, remotely-controlled drone designed for surveillance and security.": "一种小型的远程控制无人机，用于监视和安保。",
    "A repurposed fallout shelter. Cold, metallic, safe.": "一个改头换面的防空洞。冰冷，金属，安全。",
    "Add a multiplier to your Karma gains.": "在你的业力收益中增加一个乘数。",
    "Apartment in the Stacks": "书库公寓",
    "Clinic": "诊所",
    "Clinic panel": "诊所面板",
    "Criminal jobs": "犯·罪工作",
    "Get some money at the start of your life.": "在你的人生开始的时候要有一些钱。",
    "if you have enough karma to pay.": "如果你有足够的业力。",
    "In the clinic you can buy more levels for various upgrades.": "在诊所，你可以购买更多级别的各种升级。",
    "Karma multiplier": "业力乘数",
    "Level :": "等级:",
    "Level:": "等级:",
    "Life expectancy +": "预期寿命+",
    "Money at birth": "出生时的钱",
    "Price for next level:": "下一个级别的价格:",
    "Security Drone": "安保无人机",
    "Spend your karma (": "花你的业力(",
    "Stealth Suit": "隐身服",
    "Upgrade your life expectancy by 1 year.": "将你的预期寿命延长1年。",
    "We offer a large array of services": "我们提供各种各样的服务",
    "when starting a new life": "当开始新的生活",
    "x(multiplier) crime jobs XP": "x(乘数)犯·罪工作经验",
    "x(multiplier) security jobs XP": "x(乘数)安保工作经验",
    "You sell fake memory cards in the streets.": "你在街上卖假存储卡。",
    "Get a fast way to end your life.": "找一个快速的方法结束你的生命。",
    "Ohh! Him again!": "哦!又是他!",
    "Sit down, my friend.": "请坐，我的朋友。",
    "Suicide tooth": "自杀之牙",
    "(Political Influence).": "(政·治影响力)。",
    ") to get people ready to work for you. That will generate PI every time you click Activate.": ")让人们准备好为你工作。这将在每次点击激活时生成PI。",
    "/activation": "/激活",
    "╚═════ total :": "╚═════ 总计 :",
    "╠═ /click :": "╠═ /点击:",
    "╠═══ /day :": "╠═══ /每天:",
    "Activate": "激活",
    "Add one person in your organization. You'll need adequate real estate.": "在您的组织中添加一个人。你需要足够的地产。",
    "Available: 0": "可用:0",
    "Bio-Monitor": "生物监测器",
    "Buy": "购买",
    "Click the Activate button to use the infrastructure and get": "点击激活按钮使用基础设施并获得",
    "Converted Warehouse Loft": "改建仓库阁楼",
    "Create an organization": "创建一个组织",
    "Develop advanced training programs for security personnel, ensuring they're equipped with the latest techniques in cyber defense and physical combat.": "为安保人员制定先进的培训计划，确保他们配备最新的网络防御和物理作战技术。",
    "From infrastructure :": "基础设施方面:",
    "From projects :": "来自项目:",
    "In \"Infrastructure\", you'll spend Political Influence (": "在“基础设施”中，您将使用政·治影响力(",
    "In \"Projects\", use your": "在“项目”中，使用你的",
    "Infrastructure": "基础设施",
    "Levelling up in this category will upgrade the amount of PI you get every day.": "在这一类别中升级将升级你每天获得的PI数量。",
    "Levelling up in this category will upgrade the amount of PI you get from each activation.": "在此类别中升级将升级您从每次激活中获得的PI数量。",
    "Luxury Micro-Apartment": "豪华微型公寓",
    "Manage your organization here and create Political Influence.": "在这里管理你的组织，创造政·治影响力。",
    "Neuro-Stimulant": "神经兴奋剂",
    "New Power Rising": "新势力崛起",
    "Org": "组织",
    "Organization": "组织机构",
    "Organization panel": "组织委员会",
    "Paladin Protocols": "圣骑士的协议",
    "Pay in PI to build projects for your organization.": "支付PI为您的组织构建项目。",
    "Pay in PI to build the infrastructure of your organization.": "支付PI来构建组织的基础设施。",
    "Personnel :": "人员:",
    "Pills subscription II": "药丸订购II",
    "Political Influence :": "政·治影响力:",
    "Political Influence:": "政·治影响力:",
    "Projects": "项目",
    "Real estate": "房地产",
    "Recruiting": "招聘",
    "Security company": "安保公司",
    "Security jobs": "安保工作",
    "so you can gain more PI automatically with time.": "所以你可以随着时间自动获得更多的PI。",
    "Some people contacted you, there is now a possibility of creating an organization around your security work.": "有人联系了你，现在有可能围绕你的安保工作创建一个组织。",
    "The projects will create PI automatically.": "项目将自动创建PI。",
    "Type :": "类型:",
    "Upgrade the maximum possible number of recruits": "升级新兵的最大可能数量",
    "will be accounted to produce karma and the levels in your organization will unlock objects in the store.": "将被计算为产生因果报应，您组织中的级别将解锁商店中的对象。",
    "With ambition in your heart and a vision in your mind, you create an organization, attracting a diverse group of individuals to help you turn dreams into reality.": "有了心中的雄心壮志和心中的愿景，你创建了一个组织，吸引了形形色色的人来帮助你把梦想变成现实。",
    "You created an organization": "你创建了一个组织",
    "You created your first organization": "你创建了你的第一个组织",
    "You stay all night in a warehouse and hope nothing happens": "你整晚都待在仓库里，希望别出事",
    "You will lose everything about your organization when dead, but the store could have a way to prevent this.": "当你的组织死亡时，你将失去一切，但商店可以有办法防止这种情况发生。",
    "You will receive pills more often.": "你会更经常收到药片。",
    "Heist Mastery": "抢·劫精通",
    "Underworld Connections": "黑道关系",
    "✧ Scratchcard ✧": "✧刮刮卡✧",
    "A clandestine communication system immune to surveillance, ensuring safe and encrypted conversations among members.": "一个不受监视的秘密通信系统，确保成员之间的安全加密对话。",
    "A tiny box in the towering stacks. The neon lights outside never shut off.": "高耸的书架里的一个小盒子。外面的霓虹灯从不熄灭。",
    "Add a multiplier to \"Street Cred\" XP": "增加“街头信条”经验的乘数",
    "Add a multiplier to crime jobs revenue": "增加犯·罪工作收入的乘数",
    "Add a multiplier to crime jobs XP": "增加犯·罪工作经验的乘数",
    "AVAILABLE": "可用",
    "Become a seasoned criminal, adept at maximizing profits from every unlawful venture.": "成为一名经验丰富的罪犯，善于从每一次非法冒险中获利最大化。",
    "Brain Chip": "大脑芯片",
    "Crime skills": "犯·罪技能",
    "Criminal gang": "犯·罪团伙",
    "ElectroLoot Layers Scratchcard game": "电光层刮卡游戏",
    "Hidden weapons": "隐藏的武器",
    "Level : ★☆☆☆☆": "等级:★☆☆☆",
    "Nighthawk Network": "夜鹰网络",
    "Not for resale": "不得转售",
    "Scratchcard game": "刮刮卡游戏",
    "Scratcher Deluxe": "豪华刮板",
    "Some people contacted you, there is now a possibility of creating an organization around your criminal activities 🥷.": "有人联系了你，现在有可能围绕你的犯·罪活动建立一个组织🥷。",
    "Spacious, raw, with a touch of industrial aesthetics. Your haven in the urban jungle.": "宽敞，原始，带有一丝工业美学。你在都市丛林中的天堂。",
    "Submission waves emittor": "提交波发射器",
    "Suicide Tooth": "自杀之牙",
    "Terminator arms": "终结者手臂",
    "The upgrade for pro scratchers!™ Wider scratches (+20%)": "升级为专业挠痒痒!™更宽的划痕(+20%)",
    "Time to next scratchcard :": "下一张刮刮卡时间:",
    "Troll farmer": "巨魔农夫",
    "You have a scratchcard ready in the shop": "你在商店里准备好了刮刮卡",
    "Your connections in the seedy underbelly of the city pay off, yielding more valuable information and resources.": "你在城市底层的关系网会得到回报，带来更多有价值的信息和资源。",
    "Your reputation on the streets can prove to be an important asset, facilitating your advancement in the world of crime.": "你在街头的名声会成为一笔重要的财富，帮助你在犯·罪世界中取得进步。",
    "A poisoned tooth, used for a quick and - if you trust the seller - painless death.": "一颗有毒的牙齿，如果你相信卖家的话，可以快速无痛死亡。",
    "A wearable device that continuously monitors physiological information.": "一种持续监测生理信息的可穿戴设备。",
    "Add a multiplier to \"Security Protocols\" XP": "增加一个乘数\“安全协议\”XP",
    "Add a multiplier to security jobs revenue": "增加安保工作收入的乘数",
    "Add a multiplier to security jobs XP": "增加一个乘数到安保工作经验",
    "Advance your knowledge of defensive strategies, making you more valuable in the security field.": "提高你的防御策略知识，使你在安保领域更有价值。",
    "Advanced stealth suit, ideal for covert operations.": "先进的隐身服，非常适合秘密行动。",
    "Leto I's Suicide tooth": "莱托一世的自杀之牙",
    "Same thing as a classic reincarnation.": "和经典的转生一样。",
    "Security skills": "安保技能",
    "Understand and exploit the intricate security systems that protect the megacorps.": "了解并利用保护巨型军团的复杂安保系统。",
    "x(multiplier) Heist Mastery skill XP": "x(乘数)抢·劫精通技能经验",
    "x(multiplier) Vigilant Sentinel skill XP": "x(倍增器)警戒哨兵技能经验值",
    "You safeguard the lives of important and notorious figures of the city.": "你保护着这座城市中重要而臭名昭著的人物的生命。",
    "You steal small things to stay under the radar.": "你偷小东西是为了不被发现。",
    "Your alertness and tactical acumen turn every security gig into a gold mine.": "你的警觉性和战术敏锐性会让每一份安保工作都变成一座金矿。",
    "A next-generation quantum computer capable of hacking sophisticated systems.": "下一代量子计算机能够破解复杂的系统。",
    "A potent nootropic drug that enhances cognitive abilities.": "增强认知能力的强效益智药。",
    "Advanced eyewear that can analyze digital data and identify vulnerabilities.": "可以分析数字数据并识别漏洞的高级眼镜。",
    "Available: 1": "可用数量:1",
    "Life Planner": "人生规划师",
    "Organization bank": "组织银行",
    "Penthouse in a High-rise": "高层的顶层公寓",
    "Quantum PC": "量子电脑",
    "Security Drones Swarm Specialist": "安保无人机群专家",
    "Small yet modern, with smart appliances. A perfect fusion of style and technology.": "小巧而现代，配有智能家电。时尚与科技的完美融合。",
    "Stock market super AI": "股市超级人工智能",
    "x(multiplier) business jobs XP": "x(乘数)商业工作经验",
    "x(multiplier) Data Heist Pro skill XP": "x(倍增器)数据抢·劫专业技能经验",
    "x(multiplier) Focus": "x(倍增器)专注",
    "x(multiplier) hacking jobs XP": "x(乘数)黑客工作经验",
    "You get access to an exclusive AI helping on reports on market and decision-making.": "你可以访问一个独家的人工智能，帮助报告市场和决策。",
    "You'll be able to set some choices about your life.": "你将能够对你的生活做出一些选择。",
    "You'll get to keep half of the levels of your organization when reincarnated.": "当你转世时，你将保留你组织一半的等级。",
    "Retrofitted Industrial Complex": "改造工业综合体",
    "Protect corporate secrets by securing their physical and digital assets. Never a dull moment.": "通过保护公司的物理和数字资产来保护公司机密。从来都不会让人感到沉闷。",
    "A sky-high oasis with a panoramic city view. The pinnacle of metropolitan living.": "高耸入云的绿洲，城市全景尽收眼底。都市生活的巅峰。",
    "Homeless again...": "又无家可归了……",
    "Protect corporate secrets by securing their physical and digital assets. Never a dull moment.": "通过保护公司的物理和数字资产来保护公司机密。从来没有沉闷的时刻。",
    "Retrofitted Industrial Complex": "改造工业综合体",
    "The price is high, but this allow you to predict the future of the stock market.": "价格很高，但这使你可以预测股票市场的未来。",
    "x(multiplier) Merger Mogul skill XP": "x(乘数)并购大亨技能经验",
    "You have no money, so you lost your home and gear.": "你没有钱，所以你失去了你的家和装备。",
    "Get Loot!": "获取战利品!",
    "Game won !": "你赢了！",
    "BONUS! FOCUS & ALL REVENUES x": "奖励! 专注 & 所有收入 x",
    "Business": "商业",
    "Cons :": "缺点:",
    "Crime jobs experience": "犯·罪工作经历",
    "EQUIPED": "已装备",
    "NI gains from Net activities": "NI增益来自净活动",
    "Organization PI gains from projects": "组织PI增益来自项目",
    "Pros :": "优点:",
    "Security Company CEO": "安保公司CEO",
    "Security jobs experience": "安保工作经验",
    "Skill experience": "技能经验",
    "Underground Bar Proprietor": "地下酒吧老板",
    "Work experience": "工作经验",
    "Work revenue": "工作收入",
    "You manage thousands of drones that can record every movement in the city.": "你管理着上千架可以记录城市里每一个动作的无人机。",
    "You operate a clinic that offers cybernetic enhancements. Business is booming as everyone wants to be better, faster, stronger.": "你经营着一家提供强化控制技术的诊所。由于每个人都想做得更好、更快、更强，商业正在蓬勃发展。",
    "Cyber Mansion": "赛博大厦",
    "A fortress of solitude amidst the chaos. Privacy and security at its finest.": "一片混乱中，孤独的堡垒。提供最好的隐私和安全。",
    "unlocked !": "已解锁 !",
    "Only one body modification can be equiped at a time. When installed, it will last for your entire life, and adds bonus and penalties to various statistics.": "一次只能装备一种身体改装。安装后，它将持续你的整个生命，并增加奖励和惩罚的各种统计数据。",
    "Card autodestroy": "卡片自动销毁",
    "Character 2": "角色 2",
    "LOST!": "输了!",
    "ONE MODIF ONLY": "只修改一次",
    "Skill Planner": "技能规划师",
    "Sorry, game's": "对不起,游戏的",
    "UI Planner": "UI规划师",
    "Work Planner": "工作计划员",
    "You will be able to change the UI colors.": "您将能够更改UI颜色。",
    "You will be able to change to a new body.": "你将能够改变到一个新的身体。",
    "You will change job while idle.": "你会在无所事事的时候换工作。",
    "You will change the skill you're training while idle.": "闲置状态下会更换正在训练的技能",
    "base": "基础",
    "blue": "蓝色",
    "Body": "身体",
    "Character:": "角色:",
    "Crime": "犯·罪",
    "Planner": "规划师",
    "ScratchCard AutoScratch": "刮刮卡自动刮",
    "Scratchcards will have a, autoscratch function": "刮刮卡将有一个自动刮卡功能",
    "Scratcher Deluxe II": "刮刮乐豪华版 II",
    "Security": "安保",
    "The upgrade for pro scratchers!™ Wider scratches (+30%)": "专业刮刮乐升级版!™更宽的划痕(+30%)",
    "UI Theme:": "UI主题:",
    "Drug dealer": "毒·贩",
    "Gang leader": "帮会头目",
    "Implement cutting-edge surveillance systems throughout the city to deter and detect criminal activities before they unfold.": "在整个城市实施尖端的监控系统，在犯·罪活动展开之前阻止和发现犯·罪活动。",
    "It ain't much but it's... online manipulation.": "虽然不多，但是……在线操作。",
    "Script kiddy": "脚本小子",
    "Sentinel Surveillance": "哨点监测",
    "Shadow Silk Route": "暗影丝路",
    "Underground supply chains for smuggling goods, weapons, and other contraband into and out of the city.": "走私货物，武器和其他违禁品进出城市的地下供应链。",
    "You sell drugs everywhere in the city.": "你在城里到处卖毒·品。",
    "The ultimate dwelling of affluence, digitally enhanced for maximum comfort and security.": "奢华的终极居所，数码增强，最大程度的舒适和安全。",
    "You have a small team of various talents in crime.": "你有一个在犯·罪方面才华横溢的小团队。",
    "You are the leader of a security company managing all security issues for companies, individuals or public organizations.": "你是一家安保公司的领导者，负责管理公司、个人或公共组织的所有安全问题。",
    "Add a multiplier to \"Digital Shadows\" XP": "为“数字暗影”经验增加一个乘数",
    "Add a multiplier to hacking jobs revenue": "为黑客工作收入增加一个乘数",
    "Add a multiplier to hacking jobs XP": "为黑客工作经验增加一个乘数",
    "Corporate Savvy": "企业智慧",
    "Elevate your coding prowess, making you a digital force to be reckoned with.": "提高你的编码能力，使你成为一股不可忽视的数字力量。",
    "Hacking jobs": "黑客工作",
    "Hacking skills": "黑客技能",
    "Navigate the intricate webs of the net, making every hacking operation a learning experience.": "在错综复杂的网络中穿行，让每一次黑客行动都成为一次学习经历。",
    "Software Cracker": "软件破解者",
    "You are the head of a cartel of criminal organizations.": "你是一个犯·罪集团的头目。",
    "You buy scripts on the dark web, hoping they will work, and run a few scams.": "你在暗·网上购买脚本，希望它们能起作用，然后运行一些骗局。",
    "You transport sensitive data through the darkest corners of the web, bypassing every form of digital surveillance.": "你通过网络最黑暗的角落传输敏感数据，绕过各种形式的数字监控。",
    "Your expert hacking skills ensure maximum rewards from every data heist.": "你的专家黑客技能，确保从每一次数据抢·劫获得最大限度的奖励。",
    "Cybernetic Espionage Agent": "控制论间·谍特工",
    "Data Heist Pro": "数据抢·劫专业",
    "From heists on the data banks of mega-corporations to cyber warfare, you are a ghost in the machine.": "从大型企业的数据库抢·劫到网络战，你都是机器中的幽灵。",
    "Net tab": "网络标签",
    "You should build a custom computer if you're serious about hacking.": "如果你真想搞黑客的话，你应该定制一台电脑。",
    "You unlock software protections aginst copies. A few fans love you for being always the first to crack the latest upgrade of their favorite app.": "你解锁了针对拷贝的软件保护。一些粉丝喜欢你，因为你总是第一个破解他们最喜欢的应用程序的最新升级。",
    "(motherboard base + data cards) * power": "(主板底座+数据卡)*功率",
    "/unit, max:": "/单位，最大:",
    "A way to equip and store data cards.": "一种装备和存储数据卡的方法。",
    "Add Money per Second:": "每秒增加金钱:",
    "Architect of the Matrix": "黑客帝国的建筑师",
    "Attack": "攻击",
    "Attack:": "攻击:",
    "Auto attack": "自动攻击",
    "CHANGE": "更改",
    "Computer": "电脑",
    "Computer :": "电脑:",
    "Computer Shop": "电脑商店",
    "Computer Stats:": "计算机统计数据:",
    "Computing: (": "计算:(",
    "Cost Per Day:": "每日费用:",
    "cost: off": "费用:关",
    "Current cluster:": "目前集群:",
    "Data": "数据",
    "Data cards": "数据卡",
    "Data Vault": "数据保险库",
    "Datacards Effect:": "数据卡效果:",
    "Defense:": "防御:",
    "Dial-Up fossils": "拨号上网化石",
    "DOWN": "下降",
    "Equiped:": "已装备:",
    "Hacking": "黑客",
    "Hacks": "黑客",
    "Here you'll find everything about custom computers.": "在这里，您可以找到有关定制计算机的所有信息。",
    "Integrity max: (": "完整性最大: (",
    "Integrity recover: (": "完整性恢复:(",
    "Integrity Recovery:": "完整性恢复:",
    "Level max!": "等级已满!",
    "Life Expectancy:": "寿命:",
    "Maximum Integrity:": "最大的完整性:",
    "Motherboard:": "主板:",
    "Net": "网络",
    "Net Influence:": "净影响力:",
    "Network Marauder": "网络掠夺者",
    "ON/OFF": "开/关",
    "power:": "功率:",
    "Power:": "功率:",
    "Retro Realms": "复古领域",
    "Rusty microboard": "生锈的微板",
    "Script Kiddie": "脚本小子",
    "Security: (": "安全:",
    "Sell": "出售",
    "Sell a card by dropping it here.": "把卡片放在这里出售。",
    "Set cluster": "设置集群",
    "Shop Price Decrease:": "商店价格下降:",
    "Spending Money per Second:": "每秒花费的钱:",
    "Stats:": "统计:",
    "Status:": "状态:",
    "units": "单位",
    "You are an experienced hacker": "你是一个有经验的黑客",
    "You are the person that create life from nothing. It's constantly eating data and super useful. It will probably end badly of course.": "你是那个从无到有创造生命的人。它不断地消耗数据，而且非常有用。当然，结局可能很糟糕。",
    "You have your own upgradable computer": "你有自己的可升级电脑",
    "You infiltrate the digital fortresses of corporate entities and governments, silently extracting secrets that shift the power balance of the city.": "你潜入企业和政·府的数字堡垒，悄无声息地获取改变城市权力平衡的秘密。",
    "Add a multiplier to \"Corporate Savvy\" XP": "为“企业头脑”XP添加一个倍增器",
    "Add a multiplier to business jobs revenue": "增加商业工作收入的乘数",
    "Add a multiplier to business jobs XP": "增加一个乘数的业务工作XP",
    "An ancient server buzzing with the sounds of the early internet and crawling at snail pace.": "一个古老的服务器嗡嗡作响，发出早期互联网的声音，以蜗牛的速度爬行。",
    "Ancient Cyborg": "远古改造人",
    "Auto job": "自动工作",
    "Auto skill": "自动技能",
    "BOOT": "开机",
    "BOOT SEQUENCE...": "开机顺序…",
    "Business skills": "商业技能",
    "C-POWER:": "C-功率:",
    "C-SEC:": "C-秒:",
    "CONNECTED": "已连接",
    "CONNECTING": "连接中",
    "cost:": "成本:",
    "Here is my stock of computer parts.": "这是我的电脑零件存货。",
    "I'll tell you when I have new stuff.": "有新东西我会告诉你的。",
    "Integrity:": "完整性:",
    "Negotiate, manipulate, and profit. You always come out on top of every business transaction.": "谈判、操纵和获利。你总是在每笔商业交易中占上风。",
    "RUNNING": "运行",
    "Target server: (": "目标服务器:(",
    "Upgraded Expiration": "升级到期",
    "Virtual Entertainment Complex Owner": "虚拟娱乐中心负责人",
    "You don't just hack the system, you rewrite it. Laws of the digital realm bend to your will.": "你不仅要黑进系统，还要重写它。数字世界的法则会屈从于你的意志。",
    "You lived to a very old age": "你活到很老的年龄",
    "You lived to a very old age, II": "你活到很老的年龄，II",
    "Your ability to influence others and build relationships makes you a key player in the business world.": "你影响他人和建立关系的能力使你成为商业世界的关键人物。",
    "Your bar is a hub for the city’s misfits and outcasts. The drinks are strong and the secrets traded are even stronger.": "你的酒吧是城里不合群的人的聚集地。酒很烈，交易的秘密更烈。",
    "Your business acumen ensures a steep learning curve in the cutthroat corporate world.": "在竞争激烈的企业世界里，你的商业头脑保证了你有陡峭的学习曲线。",
    "You own a Virtual Reality hub, where patrons lose themselves in different realities. Reality is a commodity and you re selling it.": "你拥有一个虚拟现实中心，顾客可以在这里沉浸于不同的现实之中。现实是一种商品，而你正在出售它。",
    "You are at the helm of a megacorporation, steering the course of the city’s future. Power is your game.": "您是大型企业的掌舵人，掌控着这座城市的未来。权力就是您的游戏规则。",
    "...Loot...": "..抢·劫...",
    "A dusty corner of the internet holding a mishmash of old mp3 files.": "尘封的互联网角落里，放着一堆旧mp3文件。",
    "A forgotten database brimming with the remnants of once-popular search queries and obsolete keywords.": "一个被遗忘的数据库，充满了曾经流行的搜索查询和过时的关键字的残余。",
    "A relic filled with neon-colored backgrounds, pixelated gifs, and auto-playing MIDI tunes.": "一个充满霓虹色背景，像素化的gif和自动播放MIDI曲调的遗迹。",
    "Altavista Archives": "阿尔塔维斯塔档案",
    "ATTACKING": "攻击中",
    "Bulletin Board Bastion": "公告栏堡垒",
    "Caramail au beurre salé": "焦糖奶油色拉",
    "Chat exchanges that have frozen over into silence.": "聊天交流已经冻结为沉默。",
    "Complex networks of shared files and music, and malware.": "共享文件和音乐的复杂网络，以及恶意软件。",
    "Data Phantom": "数据幻影",
    "DEFENDING": "防御",
    "Fortified servers filled with threads and forums of a bygone era, defending old internet philosophies.": "加固的服务器充满了过去时代的线程和论坛，捍卫着旧的互联网哲学。",
    "Geocities Galaxy": "地球城市星系",
    "ICQ Ice Fields": "ICQ冰原",
    "Limewire Labyrinths": "石灰石迷宫",
    "LOOTING": "抢·劫",
    "Looting server": "抢·劫服务器",
    "Napster Nooks": "纳普斯特角落",
    "Net influence:": "净影响力:",
    "Quantum Coin Miner": "量子币矿工",
    "Qubit Compiler": "量子位编译器",
    "Scratcher Deluxe III": "豪华刮刮乐III",
    "You are a legendary hacker": "你是一个传奇的黑客",
    "Your company owns nearly everything in the world.": "你们公司几乎拥有世界上的一切。",
    "Billions of database entries consisting of \"ASV\".": "数十亿个由“ASV”组成的数据库条目。",
    "- level": "- 等级",
    "Auto": "自动",
    "A covert marketplace for trading illegal goods, services, and information.": "一个秘密交易非法商品、服务和信息的市场。",
    "A new cluster (Junkyard Junction) has been found.": "一个新的集群(废品堆积场)被发现。",
    "A software suite tailored to maximize the power of quantum hardware.": "一套专为最大限度地发挥量子硬件能力而定制的软件。",
    "Advanced tech that renders operatives virtually invisible to traditional surveillance and tracking systems.": "先进的技术可以让特工在传统的监视和跟踪系统中隐形。",
    "An abandoned digital cityscape where old social media profiles linger like ghosts in the machine.": "一个废弃的数字城市景观，旧的社交媒体资料像幽灵一样在机器中徘徊。",
    "Black Market Bazaar": "黑市集市",
    "Bonus Extension": "奖励扩展",
    "Bonus Security": "奖励保障",
    "BOSS": "Boss",
    "Cluster unlocked": "集群解锁",
    "Extension": "扩展",
    "Ghost Protocol": "幽灵协议",
    "Hidden safe houses and bases throughout the city, allowing for rapid retreats and secret meetings.": "隐藏的安全屋和基地遍布整个城市，允许快速撤退和秘密会议。",
    "Junkyard Junction": "废品堆积场",
    "Log Lagoon": "日志泻湖",
    "Meta": "元",
    "Meta tab": "元标签",
    "Mines digital currency using quantum principles, ensuring higher yield.": "利用量子原理挖掘数字货币，确保更高的收益。",
    "Myspace Metropolis": "Myspace的大都市",
    "Net Overlord": "网络霸主",
    "Org project 5 level 4": "组织 项目5 达到 4 级",
    "Organization bank II": "组织银行 II",
    "Pills subscription III": "药丸订购 III",
    "Quantum CPU": "量子CPU",
    "Quantum Quest": "量子探索",
    "Set:": "设置:",
    "Underworld Syndicate": "黑道集团",
    "Viper's Nest": "毒蛇巢穴",
    "You are the boss of a criminal organization": "你是一个犯·罪组织的老大",
    "You have hacked everything that's online": "你侵入了所有网上的东西",
    "You start your new life with the org tab unlocked, and get to keep 75% of the levels of your organization when reincarnated.": "你可以解锁组织标签开始你的新生活，并在转世时保留75%的组织级别。",
    "You’ve ascended to the pinnacle of hacking prowess, becoming a legendary figure in the digital domain. Entire networks bow to your will, and your exploits are the stuff of cyber legend. As the master of the matrix, your influence is omnipresent, your power unmatched. You are the undisputed net overlord, a virtual deity in the neon-lit world of bytes and data.": "你已经登上了黑客技术的顶峰，成为了数字领域的传奇人物。整个网络都屈从于你的意志，你的功绩成为网络传奇。作为母体的主人，你的影响力无处不在，你的力量无与伦比。您是无可争议的网络霸主，是字节和数据霓虹灯世界中的虚拟神。",
    "Defying the odds and perhaps common sense, you live to an astoundingly old age, a relic in a world of rapid obsolescence. The clinic's interventions turn you into a patchwork of flesh and circuits, each day an exercise in outlasting your warranty. Your ancient existence becomes a testament to the stubbornness of the human (and cybernetic) spirit. Eventually, you shuffle off this mortal coil, your legacy a blend of human grit and synthetic endurance.": "不顾可能性和常识，你活到了惊人的高龄，成为这个迅速过时的世界里的遗迹。诊所的干预把你变成了肉体和电路的拼凑物，每天都在锻炼你的寿命。你们古老的存在成为人类(和控制论)精神的固执的证明。最终，你摆脱尘世的束缚，你的遗产是人类的勇气和合成的耐力的混合体。",
    "hacking has become your main gig. You slip through firewalls and security protocols with practiced ease, making a decent living off your illicit activities. Your skills are honed, your confidence high, as you navigate the complex web of cyberspace like a cyber sleuth.": "黑客已经成为你的主要工作。你熟练地通过防火墙和安全协议，通过你的非法活动过上了体面的生活。当你像网络侦探一样在复杂的网络空间中穿行时，你的技能得到了磨练，你的信心高涨。",
    "Thanks to a clinic that prides itself on extending the drudgery of life, you live well past the normal expiration date. Their augmentations allow you to squeeze a few more credits out of existence and refine your skills to almost enviable levels. You become an elder of the neon streets, a master of survival hacks, until finally, the upgrades fail, and you power down for good.": "感谢一家以延长生命的苦差事而自豪的诊所，你活得很好，超过了正常的截止日期。它们的增强功能可以让你挤出更多的积分，并将你的技能提升到令人羡慕的等级。你会成为霓虹灯街道的长者，成为生存技巧的大师，直到最后，升级失败，你永远关闭电源。",
    "As an elite hacker, you’ve become a shadow over the Net, breaching clusters of servers with unparalleled finesse. Firewalls crumble before your onslaught, and no system is safe from your reach. You’re a code conqueror, revered and feared in equal measure, a phantom presence in the vast network of data.": "作为一名精英黑客，您已经成为网络上的影子，以无与伦比的技巧破坏服务器集群。防火墙在你的攻击之前就崩溃了，没有任何系统是安全的。你是一个代码征服者，既受人尊敬又令人畏惧，是庞大数据网络中的一个幽灵。",
    "Choosing a darker path, your organization evolves into a formidable criminal gang. Operations are slick and professional, and your influence spreads like a digital plague. From cyber heists to underground dealings, you’re at the helm of a shadowy empire that’s starting to run like a well-oiled machine.": "选择一条黑暗的道路，你的组织演变成一个强大的犯·罪团伙。行动圆滑而专业，你的影响力像数字瘟疫一样蔓延。从网络抢·劫到地下交易，你掌管着一个阴暗的帝国，它开始像一台运转良好的机器一样运行。",
    "Unlock the ultimate upgrades, if you have TI (Time Influence).": "拥有时间影响力(TI)时，解锁终极升级",
    "Min level:": "最低等级:",
    "With your first clunky computer, you discover the digital underworld, starting off as a fledgling hacker. Low-level servers fall prey to your basic scripts, and you revel in the thrill of your newfound power. You’re a digital delinquent, causing minor chaos and learning the ropes of this realm.": "有了你的第一台笨重的电脑，你发现了数字世界，从一个初出茅庐的黑客开始。低级服务器成为基本脚本的牺牲品，而您则陶醉于新获得的能力带来的兴奋。你是一名数码少年，制造了一些小混乱，正在学习这个领域的诀窍。",
    "A central processing unit that harnesses the power of quantum mechanics for ultra-fast computations.": "利用量子力学的力量进行超高速计算的中央处理单元。",
    "A desolate wasteland of useless backlinks and link farms that once promised SEO dominance.": "一个荒凉的荒地，无用的反向链接和链接农场，曾经承诺SEO主导地位。",
    "A system of agreements with corrupt officials and law enforcement, ensuring a level of immunity for certain operations.": "一种与腐·败·官·员和执·法·部·门达成协议的制度，确保某些行动在一定程度上不受影响。",
    "Backlink Badlands": "反向链接荒地",
    "Bonus Computing": "奖励计算",
    "Bonus Integrity": "奖励完整性",
    "Computing": "计算",
    "Crimson Contract": "深红色的合同",
    "Flash Fiefdom": "Flash领地",
    "Keyword Stuffing Stockpile": "关键词堆砌",
    "Redirect Roulette": "重定向转盘",
    "The last stronghold of outdated Flash websites, complete with intro animations and autoplay music.": "过时的Flash网站的最后据点，完成介绍动画和自动播放音乐。",
    "Unlock Net tab": "解锁网络选项卡",
    "Filled with pages so stuffed with irrelevant keywords they became unreadable.": "充斥着不相关关键字的页面，让人无法阅读。",
    "Ad Farm Acres": "广告农场英亩数",
    "Organization bank III": "组织银行 III",
    "Organization bank IV": "组织银行 IV",
    "You'll get to keep 100% of the levels of your organization when reincarnated.": "当你转世时，你将保留你组织的100%等级。",
    "You'll get to keep the upgrades to your organization when reincarnated": "当你转世时，你将保留你的组织的升级",
    "SEO Graveyard": "SEO墓地",
    "Endless logs of internet activity never purged, floating like digital driftwood.": "无穷无尽的互联网活动日志从未被清除，像数字浮木一样漂浮着。",
    "Spam Box Sanctuary": "垃圾邮件庇护所",
    "Cyber Serpent Initiative": "赛博毒蛇计划",
    "Elite hackers tasked with digital heists, espionage, and creating chaos in cyber infrastructures.": "精英黑客的任务是数字抢·劫、间·谍活动和在网络基础设施中制造混乱。",
    "Enable anti blink system on progress bars": "在进度条上启用防闪烁系统",
    "Enable Autosave (save every 5 seconds).": "启用自动保存(每5秒保存一次)。",
    "Export Game Save": "导出游戏存档",
    "Import Game Save": "导入游戏存档",
    "Tramp": "流浪汉",
    "Or if you don't have spare money, posting anywhere (social medias, forums, etc) about the game could help a lot too. Or let me know what you think of the game, or if you see bugs or problem, in the Discord server below!": "或者如果你没有多余的钱，在任何地方(社交媒体，论坛等)发布关于游戏的内容也会有很大帮助。或者让我知道你对游戏的看法，或者如果你看到错误或问题，请在下面的Discord服务器中!",
    "Released from the state’s cold embrace, you find yourself adrift in a metropolis where survival is a bitter struggle. As a tramp, the streets become your harsh tutors, teaching lessons of endurance amidst the relentless rain and flickering advertisements. Each day is a battle against hunger and despair, with progress a distant glimmer on the horizon.": "从国家的冰冷怀抱中解脱出来，你发现自己在一个生存是一场艰苦斗争的大都市中漂泊。作为一个流浪汉，街道成为你严厉的导师，在无情的雨和闪烁的广告中教会你忍耐。每一天都是一场与饥饿和绝望的战斗，进步是遥远地平线上的微光。",
    "! It would be incredibly useful and appreciated, and it is the direct way to help out the game development.": "！ 这将是非常有用和值得赞赏的，这是帮助游戏开发的直接方式。",
    "/day:": "/天:",
    "About the game": "关于游戏",
    "Hacked Clusters:": "黑客攻击集群:",
    "I'm a game dev located in France.": "我是法国的一名游戏开发者。",
    "If you want to help, consider making a donation on": "如果你想帮忙，可以考虑捐款",
    "It can be better to upgrade a job or a skill a lot instead of going to the next one as soon as possible. It may trigger unlocks or facilitate your next lives.": "最好是不断升级一项工作或技能，而不是尽快转向下一项工作。它可能会触发解锁或促进你的来生。",
    "It can be useful to rent the best house / gear possible, even if the balance is negative for some time. The focus upgrade is probably the best use for that money.": "尽可能租最好的房子/装备是很有用的，即使在一段时间内收支是负的。重点升级可能是这笔钱的最佳用途。",
    "Keep empty slots in the data cards deck.": "在数据卡组中保持空槽。",
    "Max levels (from previous lives) give a bonus % to exp gain on jobs and skills.": "最高等级(来自前世)给予工作和技能经验增益%的加成。",
    "Misc": "杂项",
    "Patreon": "Patreon",
    "Pills eaten:": "吃的药丸:",
    "Scratchcards scratched:": "刮刮乐:",
    "Timer (calc):": "计时器(calc):",
    "Timer (real):": "计时器(真实):",
    "Tips": "提示",
    "total:": "总计:",
    "Training Relaxation to high levels is useful.": "训练放松到高等级是有用的。",
    "You can buy objects in the store even after dying. Don't forget to check before a reincarnation.": "即使你死了也可以在商店里买到东西。转世前别忘了检查一下。",
    "item(s) in the store!": "商店里的物品!",
    "You can buy": "你可以购买",
    "Life expectancy:": "寿命:",
    "Reincarnations:": "转世：",
    "Tooth use:": "牙齿使用：",
    "(web)": "(网页版)",
    "All activities are organized in tabs. You can change tab by clicking the arrows, or the tab names directly. You will access new tabs after unlocking them.": "所有的活动都组织在标签中。您可以通过单击箭头或直接更改选项卡名称来更改选项卡。解锁后，您将访问新的选项卡。",
    "Close": "关闭",
    "In the Work tab, you can set your job by clicking on a line. You will gain experience points regarding that job, and after some time, level up. Your revenue depends on the job, and your level at that job.": "在工作选项卡中,您可以设置你的工作通过点击一条线。你将获得与该工作相关的经验值，并在一段时间后升级。你的收入取决于你的工作，以及你在那份工作中的水平。",
    "Disable tutorial screens": "禁用教程屏幕",
    "It is the 23rd century. The world is a brutal place where the strong prey on the weak, and survival is a daily struggle. You have nothing, no one, and nowhere to go. This world doesn’t know your name, and it doesn’t seem to care if you live or die.": "现在是23世纪。世界是一个残酷的地方，强者捕食弱者，生存是每天的斗争。你一无所有，无人陪伴，无处可去。这个世界不知道你的名字，它似乎也不在乎你的生死。",
    "New jobs are unlocked when meeting certain conditions, that you can see at the bottom of the job list.": "当满足某些条件时，新工作将被解锁，您可以在工作列表的底部看到这些条件。",
    "on most of the panels, explaining or giving details about what is happening.": "在大多数的面板上，解释或给出正在发生的事情的细节。",
    "There are Help buttons, like this:": "有帮助按钮，像这样：",
    "Welcome to Cyberpunk Life": "欢迎来到赛博朋克生活",
    "Work tab": "工作标签页",
    "You’ve been here before. Perhaps in another life, another form, but always reaching, striving for something just out of grasp. This place doesn’t remember you, yet you feel the echoes of your past selves, pulling you forward, urging you to rise.": "你以前来过这里。也许是在另一种生命，另一种形式，但总是在努力，争取一些刚刚掌握的东西。这个地方不记得你，但你能感觉到过去自己的回声，拉着你前进，催促你奋起。",
    "Enable Autosave (save every 5 seconds)": "启用自动保存（每5秒保存一次）",
    "Force desktop view (default: off)": "强制桌面视图（默认：关闭）",
    "Only one  money currency (default: off)": "只有一种货币（默认：关闭）",
    "Show tutorial windows": "显示教程窗口",
    "Superscript exponents": "上标指数",
    "Choose \"Only one money currency\" in the options to use only the base currency": "在选项中选择“只有一种货币”，只使用基础货币",
    "Game save reset": "游戏保存重置",
    "The game version was too old so the save has been reset 👷‍♂️": "游戏版本太旧，所以存档被重置了👷‍♂️",
    "with no conversion.": "没有转换。",
    "Events tab": "事件标签页",
    "Skills tab": "技能标签页",
    "Home tab": "家标签页",
    "Shop tab": "商店标签页",
    "Here you can buy items, some important, some purely optional. Try to find items that will help changing your life. Come back regularly to check out if there's new things.": "在这里你可以买到物品，一些重要的，一些纯粹是可选的。试着找到一些能改变你生活的东西。定期回来看看是否有新的东西。",
    "Hide cosmetics items": "隐藏化妆品",
    "Later, you'll unlock several Planners, allowing you to set some choices about your life.": "之后，你将解锁一些规划师，让你设置一些关于你的生活的选择。",
    "Let me know what you think of the game, or if you see bugs or problem, in the Discord server below!": "让我知道你对游戏的看法，或者如果你看到错误或问题，请在下面的Discord服务器中！",
    "Price:": "价格:",
    "These events are unlocked after major changes or discoveries in your life.": "这些事件是在你的生活发生重大变化或发现之后才会发生的。",
    "This is the event tab. It shows the main events happening in your life. Click on an item to see its description and the conditions that unlocked it.": "这是事件选项卡。它显示了你生活中发生的主要事件。点击一个项目来查看它的描述和解锁条件。",
    "Timer (adj):": "计时器(调整):",
    "You can consult items previously bought in the inventory panel.": "您可以在库存面板中查询以前购买的物品。",
    "Like jobs, new skills will be unlocked when meeting specific conditions.": "与工作一样，新技能在满足特定条件时将被解锁。",
    "More items will be unlocked as you get more money.": "当你得到更多的钱时，更多的物品将被解锁。",
    "Now that you have the Gym Access item, you can chose skills to train.": "现在您有了健身房许可物品，您可以选择要训练的技能。",
    "The Gear Renting System works the same way, but you can rent several items at the same time, and each item has a unique effect.": "装备租赁系统也是如此，但是你可以同时租用多个道具，并且每个道具都具有独特的效果。",
    "The Home Renting System allow you to chose a place to live. You will have to pay evey day, and it add to your focus, which greatly affects your performance in the Work and Skills tabs.": "房屋租赁系统允许你选择一个地方住。你必须每天付费，这增加了你的注意力，这极大地影响了你在工作和技能标签中的表现。",
    "You can change the skill you're training by selecting another line. Skills levels will affect you performance in other tabs.": "你可以通过选择另一条线来改变你正在训练的技能。技能等级会影响你在其他选项卡中的表现。",
    "There is no item you can buy in the shop.": "商店里没有你能买到的东西。",
    "Unlock the planner. You'll be able to set some choices about your life. This upgrade is necessary to create an organization.": "解锁规划师。你将能够对你的生活做出一些选择。此升级是创建组织所必需的。",
    "⇾ Karma total:": "⇾ 业力总计:",
    "After a reincarnation, the max level adds a multiplier (10% of max level) to xp gains while the job level is inferior to the max level, and 1% after.": "转世后，最高等级增加了一个乘数（最高等级的10%），而工作等级低于最高等级，之后为1%。",
    "After a reincarnation, the max level adds a multiplier (10% of max level) to xp gains while the skill level is inferior to the max level, and 1% after.": "转世后，最高等级增加一个乘数（最高等级的10%）的经验值，而技能等级低于最高等级，之后为1%。",
    "Karma after transfer:": "业力转移后:",
    "Karma per day = ((money per day / 10) + (PI per day / 100) + NI total) / 100,000,000": "每天的业力 = ((每天的钱 / 10) + (PI 每天 / 100) + NI 总计) / 100,000,000",
    "Karma this loop:": "业力在本次循环:",
    "You gain karma daily, but you'll be able to use it only after a reincarnation (it will then be transferred to the total).": "你每天获得业力，但你只能在转世之后才能使用它（然后它会被转移到总数中）。",
    "in the store!": "从商店。",
    "item(s)": "物品",
    "about an AI in the future that will judge us?": "未来的人工智能会评判我们吗？",
    "Did you hear about that rumor": "你听说那个谣言了吗",
    "Level : ★": "等级 : ★",
    "the place. I'll let you do your thing.": "这个地方。我就不打扰你了。",
    "Welcome back! You know": "欢迎回来! 你知道",
    "everyday life is just too hard for me.": "每天的生活对我来说太艰难了。",
    "Sometimes the regularness of": "有时规律的",
    "Hey chief.": "嘿，长官。",
    "How are things for you?": "你过得怎么样？",
    "Buy item Life Planner": "购买物品生活规划师",
    "Buy item Work Planner": "购买物品工作规划师",
    "Buy item Skill Planner": "购买物品技能规划师",
    "House Planner": "房子规划师",
    "You will be able to change to a new body. Cosmetic change only.": "你将能够改变到一个新的身体。只是表面上的改变。",
    "You will change home while idle, depending on your money net revenue.": "你会在空闲的时候换家，这取决于你的净收入。",
    "Body:": "身体:",
    "Create Criminal Org": "创建犯·罪组织",
    "Create Security Org": "创建安全组织",
    "From infrastructure:": "来自基础设施：",
    "Oooh! Him again!": "噢!又是他！",
    "From projects:": "来自项目：",
    "Organization tab": "组织标签页",
    "This moment, exactly.": "正是此刻。",
    "Type:": "类型:",
    "Base price:": "基础价格:",
    "Clinic tab": "诊所标签页",
    "Effect /level:": "效果 /等级:",
    "Beneath the bustling data streams lies a crypt of forgotten cryptocurrencies and blockchain relics. Hackers mine for lost wallets and ghost transactions that whisper secrets of the old financial frontier.": "在熙熙攘攘的数据流之下，隐藏着被遗忘的加密货币和区块链遗迹。黑客们挖掘丢失的钱包和隐藏着旧金融前沿秘密的幽灵交易。",
    "From a humble startup to a multinational powerhouse, your security company now spans the globe. Branches in every major city, contracts with top-tier clients, and a network of professionals all dedicated to one mission: securing the future. You’ve crafted an empire of protection, a beacon of safety in a chaotic world.": "从一个不起眼的初创公司到一家跨国公司，你的安全公司现在遍布全球。在每个主要城市都设有分支机构，与顶级客户签订合同，以及一个专业人士网络，所有这些都致力于一个使命：确保未来。你创造了一个保护的帝国，一个混乱世界中的安全灯塔。",
    "This motherboard boasts moderate processing capabilities and supports multiple upgrade slots. Its sleek design is popular among intermediate hackers seeking reliability and performance": "这款主板拥有中等的处理能力，并支持多个升级槽。其时尚的设计在追求可靠性和性能的中级黑客中很受欢迎",
    "This motherboard is equipped with the latest chromatic processors, enabling lightning-fast data processing and seamless multitasking. Its extensive upgrade options make it a top choice for elite hackers.": "这款主板配备了最新的彩色处理器，可实现闪电般快速的数据处理和无缝多任务处理。其广泛的升级选项使其成为精英黑客的首选。",
    "With its cutting-edge data transmission capabilities, this motherboard provides exceptional performance and versatility. It's a favorite among professional hackers for its balance of power and adaptability.": "凭借其尖端的数据传输能力，这款主板提供了卓越的性能和多功能性。它是专业黑客的最爱，因为它的平衡能力和适应性。",
    "Your criminal gang grows into a sprawling cartel, its reach extending to every corner of the globe. With operations in multiple continents, your influence is inescapable, your power undeniable. You are the mastermind behind a vast network of illicit activities, a true architect of the underworld.": "你的犯罪团伙成长为一个庞大的卡特尔，它的触角延伸到地球的每一个角落。你的业务遍及多个大洲，你的影响力不可避免，你的力量不可否认。你是一个庞大的非法活动网络背后的策划者，一个真正的地下世界的建筑师。",
    "Your organization pivots to focus on security, and business starts to boom. Contracts flow in, and your company earns a reputation for being the go-to for safeguarding assets in this digital age. You’re building a fortress, brick by digital brick, as the demand for your services surges.": "您的组织转向关注安全性，业务开始蓬勃发展。合同源源不断，你的公司赢得了在这个数字时代保护资产的声誉。随着对你的服务的需求激增，你正在一砖一瓦地建造一座堡垒。",
    "Silk Road Ruins": "丝绸之路遗址",
    "A graveyard of failed Initial Coin Offerings, where token promises are as empty as the virtual coins they sold.": "一个失败的首次代币发行（ico）的墓地，在那里，象征性的承诺就像他们出售的虚拟货币一样空洞。",
    "Altcoin Alcoves": "山寨币壁龛",
    "Bio Body": "生物的身体",
    "black & white": "黑白照片",
    "BONUS! FOCUS & ALL REVENUES": "奖金!专注和所有收益",
    "brown": "棕色（的）",
    "Business Jobs are unlocked at start": "业务任务在开始时解锁",
    "Business Lord": "业务主",
    "Business Lord - Foundation": "商业勋爵-基金",
    "Business Lord Chip": "商业领主Chip",
    "Cartel Dominion": "卡特尔统治",
    "Chromatic Overdrive": "彩色超速",
    "Criminal org": "犯罪组织",
    "Crypto Crypt": "加密地下室",
    "Cyborg Body": "半机械人身体",
    "CyPop Alpha": "赛普阿尔法",
    "Digital archives of infamous pump-and-dump schemes, a wild west of speculative crypto bubbles.": "臭名昭著的泵和转储计划的数字档案，投机加密泡沫的狂野西部。",
    "EQUIPPED": "装备",
    "Equipped !": "装备!",
    "Exchange Exodus": "外汇外流",
    "Find clusters of servers and hack them all.": "找到服务器集群并破解它们。",
    "Forked Fantasies": "分叉的幻想",
    "Global Security Solutions": "全球安全解决方案",
    "Hacktivist Haven": "黑客天堂",
    "Hyperwave Nexus": "超波联系",
    "ICO Island": "ICO岛",
    "ICO Island | 100%": "ICO岛| 100%",
    "Lost Ledger Labyrinth": "遗失分类帐迷宫",
    "Mining Malware Mines": "挖掘恶意软件",
    "Neon Byteboard": "霓虹灯Byteboard",
    "Only one body modification can be equipped at a time. When installed, it will last for your entire life, and adds bonus and penalties to various statistics.": "一次只能装备一种身体改装。安装后，它将持续你的整个生命，并增加奖励和惩罚的各种统计数据。",
    "Organisations:": "组织:",
    "Projects:": "项目:",
    "Quantum Syncboard": "量子同步板",
    "Recruits:": "招聘:",
    "Security Inc.": "安全公司。",
    "Security org": "安全组织",
    "Servers status:": "服务器状态:",
    "The game has been imported and loaded 👌": "游戏已经导入并加载👌",
    "This motherboard offers enhanced speed and efficiency. It supports a wide range of upgrades, making it ideal for more complex hacking operations.": "这款主板提供了更高的速度和效率。它支持广泛的升级，使其成为更复杂的黑客行动的理想选择。",
    "This Thing of Ours": "我们的东西",
    "Upgrade your computer by installing a new motherboard, and data cards (in the Data tab).": "通过安装新的主板和数据卡（在“数据”选项卡中）来升级计算机。",
    "violet": "紫罗兰色的",
    "Whale Wallet Waters": "鲸鱼钱包水域",
    "Whale Wallet Waters | 100%": "鲸鱼钱包水| 100%",
    "When you meet the conditions to make an object buyable, it will stay buyable after a reincarnation.": "当你满足了使一个对象可购买的条件时，它将在转世后保持可购买状态。",
    "You are an important player in world economy.": "你们是世界经济的重要参与者。",
    "You are the boss of a criminal organization, II": "你是一个犯罪组织的老大",
    "You can hack servers using your computer, and gain Net Influence.": "你可以用你的电脑入侵服务器，获得网络影响力。",
    "You lead a security organization": "你领导着一个安全组织",
    "You lead a security organization, II": "你领导着一个安全组织，II",
    "You will be able to change to a new type of body. Cosmetic change only.": "你将能够变成一种新的身体。只是表面上的改变。",
    "You will get a 20% bonus on Business Jobs XP": "你将获得20%的商业工作XP奖励",
    "You're in the 0.1%": "你在0.1%",
    "↳ incl. Partners Board:": "（包括合伙人董事会）",
    "A dedicated anti-corruption unit tasked with maintaining the integrity of both public and private sectors.": "一个专责反贪小组，负责维护公营及私营机构的廉洁。",
    "A fleet of surveillance drones equipped with non-lethal tools for crowd control and monitoring.": "配备非致命工具的无人侦察机编队，用于人群控制和监控。",
    "A network of fortified security checkpoints ensuring regulated movement and a rapid response to potential threats.": "一个加强的安全检查站网络，确保有规律的行动和对潜在威胁的快速反应。",
    "A specialized task force trained to handle high-risk situations involving major criminal elements.": "训练有素的处理涉及重大犯罪分子的高风险情况的特别工作队。",
    "Advanced biometric and AI-driven entry systems for critical city zones, ensuring only authorized personnel have access.": "先进的生物识别和人工智能驱动的门禁系统，确保只有授权人员才能进入。",
    "Civic Shield Workshops": "市民盾牌工作坊",
    "Collaborative efforts with local businesses to fund and support security advancements in their respective sectors.": "与当地企业合作，资助和支持各自行业的安全进步。",
    "Community outreach centers aiming to bridge the gap between security forces and the general populace, fostering trust and cooperation.": "社区外展中心旨在弥合安全部队与普通民众之间的差距，促进信任与合作。",
    "Cyber Safeguard Initiative": "网络安全倡议",
    "Dedicated cyber teams focused on safeguarding critical infrastructures against digital threats and breaches.": "专门的网络团队专注于保护关键基础设施免受数字威胁和破坏。",
    "Dove Drones": "鸽子无人机",
    "Guarded Gateway": "有守卫的网关",
    "Guardian Grid": "守护网格",
    "Harmony Hub": "和谐枢纽",
    "Invest in AI-driven lie detection and interrogation tools, ensuring swift and just investigations.": "投资人工智能驱动的测谎和审讯工具，确保迅速公正的调查。",
    "Justice Javelin": "正义标枪",
    "Peacekeeper Partnerships": "维和人员合作",
    "Public workshops designed to educate citizens on safety measures, self-defense, and how to cooperate with security forces.": "举办公共讲习班，教育公民安全措施、自卫以及如何与安全部队合作。",
    "Purity Project": "纯洁的项目",
    "Truthseeker Tech": "真理的科技",
    "An organic layer designed to boost the computer's resilience by mimicking neural patterns.": "这是一种有机层，通过模仿神经模式来增强计算机的弹性。",
    "Bonus card": "奖励卡",
    "Bonus Computing x1": "奖励计算x1",
    "Cards Collection": "卡片收集",
    "Converts cognitive effort into in-game currency.": "将认知努力转化为游戏货币。",
    "Destroy": "摧毁",
    "Equip Gear cards to upgrade your computer's statistics. Or merge them on a identical card to level up and upgrade the bonus slots capacity.": "装备齿轮卡升级您的计算机的统计数据。或者将它们合并在一张相同的卡牌上以升级并升级奖励插槽容量。",
    "Equipped:": "装备:",
    "Gear card": "装备卡",
    "Gear Cards": "装备卡",
    "Integrity": "完整性",
    "Merge Bonus cards to Gear cards to fill the (corresponding type) bonus slot.": "合并奖励卡到装备卡，以填补（相应类型）奖励槽。",
    "Merge this card on a Gear card with a Bonus Computing slot to add 1 point": "合并这张卡在齿轮卡与奖金计算插槽，以增加1点",
    "Merge this card on a Gear card with a Bonus Extension slot to add 1 point": "合并这张卡上的齿轮卡与奖金扩展插槽，以增加1点",
    "Merge this card on a Gear card with a Bonus Integrity slot to add 1 point": "将这张卡合并到带有奖励完整性插槽的齿轮卡上，可以增加1点",
    "Merge this card on a Gear card with a Bonus Security slot to add 1 point": "合并这张卡上的齿轮卡与奖金安全插槽，以增加1点",
    "Neural Nexus": "神经连结",
    "Neuro-Crypto Converter": "神经密码转换器",
    "Synaptic Shield": "突触的盾牌",
    "Upgrade Cards": "升级卡",
    "An implant that increases the user's learning speed and capacity.": "一种能提高使用者学习速度和能力的植入物。",
    "Auto house": "汽车的房子",
    "Cybernetics Clinics Owner": "控制论诊所老板",
    "Knowledge Enhancer": "知识增强剂",
    "Pharma Heir": "制药公司的继承人",
    "x(multiplier) all skill XP": "x（乘数）所有技能经验值",
    "Add a multiplier to ": "添加一个乘数到",
    "Destroy a card by dropping it here.": "把一张卡丢在这里就可以毁掉它。",
    "New card:": "新卡:",
    "Twisting networks of lost blockchain ledgers that still whisper of fortunes never claimed.": "由丢失的区块链分类账组成的扭曲网络，仍在低语着从未有人认领的财富。",
    "You operate several giant clinics that offer cybernetic enhancements. Business is booming as everyone wants to be better, faster, stronger.": "你经营着几家提供强化控制的大型诊所。由于每个人都想做得更好、更快、更强，商业正在蓬勃发展。",
    "the digital equivalent of your grandma's attic, but with fewer cobwebs and more dial-up tones. This cluster is a neon-drenched museum of ancient memes, early-day blogs, and the wild wilderness of web 1.0.": "数字版的你奶奶的阁楼，但少了蜘蛛网，多了拨号铃声。这个集群是一个霓虹灯洋溢的博物馆，里面有古老的表情包、早期的博客和web 1.0的荒野。",
    "A chaotic archive of discarded tech and obsolete data.": "一个由废弃技术和过时数据组成的混乱档案。",
    "A glorified Pi | 25%": "光荣的Pi | 25%",
    "A social club. You're not invited.": "社交俱乐部你没被邀请。",
    "Anarchist Archive": "无政府主义者存档",
    "Carbon Footprint Crusaders": "碳足迹斗士",
    "Clandestine Code Collective": "秘密代码小组",
    "Corporate Sabotage Server": "企业破坏服务器",
    "Digital Dumpster Divers": "数字垃圾箱潜水员",
    "Eco-Encrypt Enclave": "生态加密飞地",
    "Fed Finder Forums | 25%": "美联储发现者论坛 | 25%",
    "Hacktivist History Hub": "黑客主义历史中心",
    "La Cosa Nostra Cloud | 50%": "黑手党云 | 50%",
    "Loan Shark Ledger | 50%": "高利贷分类账 | 50%",
    "Olive Oil Online | 25%": "橄榄油在线 | 25%",
    "Open Source Outpost": "开源前哨",
    "Push it to the limit | 25%": "把它推到极限 | 25%",
    "The Bada Bing Soft suite": "八达冰软套房",
    "The underground servers where digital rebels plot and plan. This cluster is a hub for cyber-revolutionaries looking to make a mark on the world, one hack at a time.": "数字叛军策划和计划的地下服务器。这个集群是网络革命者的中心，他们希望在世界上留下印记，一次一个黑客。",
    "Vegan Hack Vineyard": "素食黑客葡萄园",
    "Web Ring Relics": "网环遗迹",
    "A motley crew of activists looking for reusable code in the trash tiers of the internet.": "一群形形色色的积极分子在互联网的垃圾层中寻找可重用的代码。",
    "Importing scratch card...": "导入刮刮卡…",
    "Strip club management software.": "脱·衣·舞俱乐部管理软件。",
    "After a few decades of life, your journey ends with a standard-issue expiration notice. You reflect on a life of mundane compliance, while your heart is ceasing its beats in a second. The city is of course indifferent to your departure.": "经过几十年的生活，你的旅程以一份标准的到期通知结束。当你的心脏在一秒钟内停止跳动时，你反思着世俗的顺从生活。这座城市当然不会在意你的离去。",
    "In the sterile, neon-lit corridors of child-producing facility #711, you come into existence. Strangely, the processus of insemination took 0.8 seconds more than expected. The machinery hums, a line reporting the anomaly appears somewhere on a server log, and you are cast into the sprawling, brutalist cityscape, barely more than your ID number.": "在711号生育设施的无菌、霓虹灯照亮的走廊里，你诞生了。奇怪的是，授精过程比预期多花了0.8秒。机器嗡嗡作响，服务器日志上某处出现了一条报告异常的行，你被扔进了杂乱无章的野兽派城市景观中，只比你的身份证号码多一点点。",
    "Skip": "跳过",
    "Released from CPF #711 cold embrace, you find yourself adrift in a metropolis where survival is a bitter struggle. As a tramp, the streets become your harsh tutors, teaching lessons of endurance amidst the relentless rain and flickering advertisements. Each day is a battle against hunger and despair, with progress a distant glimmer on the horizon.": "从cpf# 711的冰冷怀抱中释放出来，你发现自己在一个生存是一场艰苦斗争的大都市中漂泊。作为一个流浪汉，街道成为你严厉的导师，在无情的雨和闪烁的广告中教会你忍耐。每一天都是一场与饥饿和绝望的战斗，进步是遥远地平线上的微光。",
    "#Rent4Life": "#最近4次人生",
    "+ Unlocked new tips in the Misc tab.": "+ 解锁新的提示在杂项标签页。",
    "Background animation": "背景动画",
    "Base stats:": "基础统计数据：",
    "Game start date:": "游戏开始日期：",
    "Hide": "隐藏",
    "It may be better to upgrade a job or a skill a lot instead of going to the next one as soon as possible. It may trigger unlocks or facilitate your next lives.": "最好是把一份工作或一项技能升级很多，而不是尽快转向下一份工作。它可能会触发解锁或促进你的来生。",
    "It would be incredibly useful and appreciated, and it is the direct way to help out the game development.": "这将是非常有用和值得赞赏的，这是帮助游戏开发的直接方式。",
    "Life Recap": "人生回顾",
    "New Jobs max levels:": "新工作最高级别：",
    "New Skills max levels:": "新技能最高等级：",
    "Timer:": "计时器：",
    "Unlocked": "解锁",
    "years old.": "岁了。",
    "Use your last years of living, when you have high levels of focus, to upgrade old jobs and pass on them faster on the next lives.": "利用你生命的最后几年，当你高度专注的时候，升级旧的工作，并在下辈子更快地把它们传递下去。",
    "You should make specialized lives sometimes, to upgrade a specific job or skill so it will be faster on the next reincarnations.": "有时候你应该创造一些特殊的生命，去升级一项特定的工作或技能，这样在下一次转世时就会更快。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Programmed by Markadet, 2024.": "Programmed by Markadet, 2024.",
    "OmniCartel CEO": "奥姆尼卡特尔CEO",
    "Megacorp CEO": "巨型企业CEO",
    "Merger Mogul": "并购大亨",
    "Influence Broker": "影响力经纪人",
    "AI specialist": "AI专家",
    "Elite Hacker": "精英黑客",
    "Data Smuggler": "数据走私者",
    "Digital Shadows": "数字暗影",
    "Criminal consortium president": "犯·罪集团总裁",
    "Code Guru": "代码大师",
    "Business super AI": "商业超级AI",
    "Cybernetics Clinic Owner": "控制论诊所老板",
    "Data-Goggles": "数据护目镜",
    "Security Protocols": "安保协议",
    "Bodyguard for Hire": "雇佣保镖",
    "Vigilant Sentinel": "警戒哨兵",
    "Security Consultant": "安全顾问",
    "Defensive Specialist": "防守专家",
    "Thief": "窃贼",
    "Scammer": "骗子",
    "Factory worker": "工厂工人",
    "Frugality": "节俭",
    "Kitchen worker": "厨房员工",
    "Relaxation": "放松",
    "Logic": "逻辑",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "App slave": "应用程序奴隶",
    "Years before next level: ": "距离下一级年数：",
    "Days before next level: ": "距离下一级天数：",
    "Beggar - ": "乞丐 - ",
    "Relaxation - ": "放松 - ",
    "Troll farmer - ": "巨魔农夫 - ",
    "Integrity - ": "完整性 - ",
    "Thief - ": "窃贼 - ",
    "Tramp - ": "流浪汉 - ",
    "Corporate Savvy - ": "企业智慧 - ",
    "Scammer - ": "骗子 - ",
    "Merger Mogul - ": "并购大亨 - ",
    "Logic - ": "逻辑 - ",
    "Virtual Entertainment Complex Owner - ": "虚拟娱乐中心负责人 - ",
    "Megacorp CEO - ": "巨型企业CEO - ",
    "Architect of the Matrix - ": "黑客帝国的建筑师 - ",
    "Elite Hacker - ": "精英黑客 - ",
    "Charisma - ": "魅力 - ",
    "OmniCartel CEO - ": "奥姆尼卡特尔CEO - ",
    "Vigilant Sentinel - ": "警戒哨兵 - ",
    "Cybernetics Clinic Owner - ": "控制论诊所老板 - ",
    "Underworld Connections - ": "黑道关系 - ",
    "Street Cred - ": "街头信条 - ",
    "Factory worker - ": "工厂工人 - ",
    "Gang leader - ": "帮会头目 - ",
    "Security Company CEO - ": "安保公司CEO - ",
    "Criminal consortium president - ": "犯·罪集团总裁 - ",
    "Frugality - ": "节俭 - ",
    "Underground Bar Proprietor - ": "地下酒吧老板 - ",
    "Influence Broker - ": "影响力经纪人 - ",
    "Software Cracker - ": "软件破解者 - ",
    "Cybernetic Espionage Agent - ": "控制论间·谍特工 - ",
    "AI specialist - ": "AI专家 - ",
    "Data Smuggler - ": "数据走私者 - ",
    "Script kiddy - ": "脚本小子 - ",
    "Digital Shadows - ": "数字暗影 - ",
    "Data Heist Pro - ": "数据抢·劫专业 - ",
    "Code Guru - ": "代码大师 - ",
    "Drug dealer - ": "毒·贩 - ",
    "Security Protocols - ": "安保协议 - ",
    "Bodyguard for Hire - ": "雇佣保镖 - ",
    "Security Consultant - ": "安全顾问 - ",
    "Defensive Specialist - ": "防守专家 - ",
    "Security Drones Swarm Specialist - ": "安全无人机蜂群专家 - ",
    "Heist Mastery - ": "抢·劫精通 - ",
    "Security agent by night - ": "夜间安保人员 - ",
    "Kitchen worker - ": "厨房员工 - ",
    "Software Cracker lvl ": "软件破解者 等级 ",
    "Architect of the Matrix lvl ": "黑客帝国的建筑师 等级 ",
    "Virtual Entertainment Complex Owner lvl ": "虚拟娱乐中心负责人 等级 ",
    "AI specialist lvl ": "AI专家 等级 ",
    "Megacorp CEO lvl ": "巨型企业CEO 等级 ",
    "Heist Mastery lvl ": "抢·劫精通 等级 ",
    "Factory worker lvl ": "工厂工人 等级 ",
    "Drug dealer lvl ": "毒·贩 等级 ",
    "OmniCartel CEO lvl ": "奥姆尼卡特尔CEO 等级 ",
    "Cybernetic Espionage Agent lvl ": "控制论间·谍特工 等级 ",
    "Relaxation lvl ": "放松 等级 ",
    "Corporate Savvy lvl ": "企业智慧 等级 ",
    "Influence Broker lvl ": "影响力经纪人 等级 ",
    "Merger Mogul lvl ": "并购大亨 等级 ",
    "Elite Hacker lvl ": "精英黑客 等级 ",
    "Underworld Connections lvl ": "黑道关系 等级 ",
    "Security agent by night lvl ": "夜间安保人员 等级 ",
    "Street Cred lvl ": "街头信条 等级 ",
    "Security Drones Swarm Specialist lvl ": "安保无人机群专家 等级 ",
    "Security Company CEO lvl ": "安保公司CEO 等级 ",
    "Code Guru lvl ": "代码大师 等级 ",
    "Criminal consortium president lvl ": "犯·罪集团总裁 等级 ",
    "Data Heist Pro lvl ": "数据抢·劫专业 等级 ",
    "Digital Shadows lvl ": "数字暗影 等级 ",
    "Script kiddy lvl ": "脚本小子 等级 ",
    "Data Smuggler lvl ": "数据走私者 等级 ",
    "Frugality lvl ": "节俭 等级 ",
    "Underground Bar Proprietor lvl ": "地下酒吧老板 等级 ",
    "Gang leader lvl ": "帮会头目 等级 ",
    "Cybernetics Clinic Owner lvl ": "控制论诊所老板 等级 ",
    "Security Protocols lvl ": "安保协议 等级 ",
    "Logic lvl ": "逻辑 等级 ",
    "Security Consultant lvl ": "安全顾问 等级 ",
    "Troll farmer lvl ": "巨魔农夫 等级 ",
    "Thief lvl ": "窃贼 等级 ",
    "Bodyguard for Hire lvl ": "雇佣保镖 等级 ",
    "Vigilant Sentinel lvl ": "警戒哨兵 等级 ",
    "Beggar lvl ": "乞丐 等级 ",
    "Defensive Specialist lvl ": "防守专家 等级 ",
    "Scammer lvl ": "骗子 等级 ",
    "Kitchen worker lvl ": "厨房员工 等级 ",
    "Math.max(1 - Math.log(level ": "Math.max(1 - Math.log(等级 ",
    "Multiplier: 1 + (level ": "乘数: 1 + (等级 ",
    "You died at ": "你活到了 ",
    "Slots: ": "槽位: ",
    "Bonus Extension x": "奖励扩展 x",
    "Bonus Integrity x": "奖励完整性 x",
    "Bonus Security x": "奖励安保 x",
    "→ exp  * 1 + (maxLevel / ": "→ 经验值  * 1 + (最大等级 / ",
    "After level is over max level: ": "等级超过最大等级后: ",
    "Before max level is reached: ": "在达到最大等级之前: ",
    "Pump-and-Dump Pits": "泵和倾倒坑",
    "Cybernetics Clinics Owner lvl ": "控制论诊所老板等级 ",
    "Cybernetics Clinics Owner - ": "控制论诊所老板等级 - ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    " (DEAD)": " (死亡)",
    "\"Digital Shadows\" XP": "“数字阴影” 经验",
    "hacking jobs revenue": "黑客工作收入",
    " | 100%": " | 100%",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^ x ([\d\.]+)$/,
    /^→ ([\d\.]+)$/,
    /^→ x ([\d\.]+)$/,
    /^→ x ([\d\.]+)K$/,
    /^→ x ([\d\.]+)B$/,
    /^→ x ([\d\.]+)M$/,
    /^\+ ([\d\.]+) \%$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)T$/,
    /^([\d\.]+)Qa$/,
    /^([\d\.]+)Qi$/,
    /^([\d\.]+)Sx$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+) $/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\[([\d\.,]+)\] \* ([\d\.]+)\)$/,
    /^\[([\d\.,]+)\]\) \/ ([\d\.,]+), ([\d\.]+)\)$/,
    /^ \- ([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Adds (.+) to the output of Project (.+)$/, '将项目 $2 的产出增加 $1'],
    [/^Org project (.+) level (.+)$/, '组织项目 $1 达到等级 $2'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Get Project (.+) to level (.+)$/, '将项目 $1 提升到 $2 级'],
    [/^Get to level (.+) Cybernetics Clinic Owner$/, '升级到 $1 级 控制论诊所老板'],
    [/^Get to level (.+) Software Cracker$/, '升级到 $1 级 软件破解者'],
    [/^Get to level (.+) Security Drones Swarm Specialist$/, '升级到 $1 级 安保无人机蜂群专家'],
    [/^Get to level (.+) Security Consultant$/, '升级到 $1 级 安全顾问'],
    [/^Get to level (.+) Cybernetics Clinics Owner$/, '升级到 $1 级 控制论诊所老板'],
    [/^Get to level (.+) Data Smuggler$/, '升级到 $1 级 数据走私者'],
    [/^Get to level (.+) Kitchen worker$/, '升级到 $1 级 厨房员工'],
    [/^Get to level (.+) Security Company CEO$/, '升级到 $1 级 安保公司CEO'],
    [/^Get to level (.+) Criminal consortium president$/, '升级到 $1 级 犯·罪集团总裁'],
    [/^Get to level (.+) Security agent by night$/, '升级到 $1 级 夜间安保人员'],
    [/^Get to level (.+) Cybernetic Espionage Agent$/, '升级到 $1 级 控制论间·谍特工'],
    [/^Get to level (.+) AI specialist$/, '升级到 $1 级 AI专家'],
    [/^Get to level (.+) Elite Hacker$/, '升级到 $1 级 精英黑客'],
    [/^Get to level (.+) Bodyguard for Hire$/, '升级到 $1 级 雇佣保镖'],
    [/^Get to level (.+) Gang leader$/, '升级到 $1 级 帮会头目'],
    [/^Get to level (.+) Script kiddy$/, '升级到 $1 级 脚本小子'],
    [/^Get to level (.+) Architect of the Matrix$/, '升级到 $1 级 黑客帝国建筑师'],
    [/^Get to level (.+) Drug dealer$/, '升级到 $1 级 毒·贩'],
    [/^Get to level (.+) Scammer$/, '升级到 $1 级 骗子'],
    [/^Get to level (.+) Thief$/, '升级到 $1 级 窃贼'],
    [/^Get to level (.+) Beggar$/, '升级到 $1 级 乞丐'],
    [/^Get to level (.+) Tramp$/, '升级到 $1 级 流浪汉'],
    [/^Get to level (.+) App slave$/, '升级到 $1 级 应用程序奴隶'],
    [/^Get to level (.+) App Slave$/, '升级到 $1 级 应用程序奴隶'],
    [/^\→ exp multiplied by: (.+) \+ \(maxLevel \/ (.+)\)$/, '→ 经验乘以：$1 \+ （最大等级 \/ $2）'],
    [/^PI \/ click: (.+) x (.+) \(x(.+)\)$/, 'PI / 点击: $1 x$2 (x$3)'],
    [/^PI \/ day: (.+) x (.+) \(x(.+)\)$/, 'PI / 天: $1 x$2 (x$3)'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^x([\d\.]+) basic jobs XP$/, 'x$1 基础工作经验'],
    [/^x([\d\.]+) skill XP$/, 'x$1 技能经验'],
    [/^x([\d\.]+) Merger Mogul skill XP$/, 'x$1 并购大亨技能经验'],
    [/^x([\d\.]+) Data Heist Pro skill XP$/, 'x$1 数据抢·劫专业技能经验'],
    [/^x([\d\.]+) work XP$/, 'x$1 工作经验'],
    [/^x([\d\.]+) \"Digital Shadows\" XP$/, 'x$1 “数字暗影”经验'],
    [/^x([\d\.]+) \"Corporate Savvy\" XP$/, 'x$1 “企业智慧”经验'],
    [/^x([\d\.]+) \"Street Cred\" XP$/, 'x$1 “街头信条”经验'],
    [/^x([\d\.]+) \"Security Protocols\" XP$/, 'x$1 “安保协议”经验'],
    [/^x([\d\.]+) Vigilant Sentinel skill XP$/, 'x$1 警戒哨兵技能经验'],
    [/^x([\d\.]+) Heist Mastery skill XP$/, 'x$1 抢·劫精通技能经验'],
    [/^x([\d\.]+) business jobs XP$/, 'x$1 商业工作经验'],
    [/^x([\d\.]+) hacking jobs XP$/, 'x$1 黑客工作经验'],
    [/^x([\d\.]+)(.+)hacking jobs XP$/, 'x$1$2黑客工作经验'],
    [/^x([\d\.]+) crime jobs XP$/, 'x$1 犯·罪工作经验'],
    [/^x([\d\.]+) security jobs XP$/, 'x$1 安保工作经验'],
    [/^x([\d\.]+) Focus$/, 'x$1 专注'],
    [/^x([\d\.]+) expenses$/, 'x$1 支出'],
    [/^x([\d\.]+) business jobs revenue$/, 'x$1 商业工作收入'],
    [/^x([\d\.]+) security jobs revenue$/, 'x$1 安保工作收入'],
    [/^x([\d\.]+) hacking jobs revenue$/, 'x$1 黑客工作收入'],
    [/^x([\d\.]+) crime jobs revenue$/, 'x$1 犯·罪工作收入'],
    [/^x([\d\.]+) work revenue$/, 'x$1 工作收入'],
    [/^x([\d\.]+)(.+)work XP$/, 'x$1$2工作经验'],
    [/^x([\d\.]+)(.+)skill XP$/, 'x$1$2技能经验'],
    [/^x([\d\.]+)(.+)\"Street Cred\" XP$/, 'x$1$2“街头信条”经验'],
    [/^x([\d\.]+)(.+)\"Security Protocols\" XP$/, 'x$1$2“安全协议”经验'],
    [/^x([\d\.]+)(.+)security jobs XP$/, 'x$1$2安保工作经验'],
    [/^x([\d\.]+)(.+)expenses$/, 'x$1$2费用'],
    [/^x([\d\.]+)(.+)crime jobs XP$/, 'x$1$2犯罪工作经验'],
    [/^x([\d\.]+)(.+)crime jobs revenue$/, 'x$1$2犯罪工作收入'],
    [/^x([\d\.]+)(.+)security jobs revenue$/, 'x$1$2安保工作收入'],
    [/^x([\d\.]+)(.+)work revenue$/, 'x$1$2工作收入'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) recruits in org$/, '$1 组织新人'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\+ ([\d\.,]+) years$/, '\+ $1 年'],
    [/^\+ ([\d\.,]+)(.+) years$/, '\+ $1$2 年'],
    [/^Tramp lvl ([\d\.,]+)$/, '流浪汉 等级 $1'],
    [/^([\d\.,]+)(.+)$/, '$1$2'],
    [/^\-([\d\.,]+)(.+)$/, '\-$1$2'],
    [/^→ x ([\d\.,]+)(.+)$/, '→ x $1$2'],
    [/^ \- ([\d\.,]+)(.+)$/, ' \- $1$2'],
    [/^\+ ([\d\.,]+) years$/, '\+ $1 年'],
    [/^Hack Cluster ([\d\.,]+)$/, '黑客集群 $1'],
    [/^Security Project ([\d\.,]+)$/, '安保项目 $1'],
    [/^Body ([\d\.,]+)$/, '身体 $1'],
    [/^Character ([\d\.,]+)$/, '角色 $1'],
    [/^motherboard ([\d\.,]+)$/, '主板 $1'],
    [/^Available: ([\d\.,]+)$/, '可用: $1'],
    [/^Available: \-([\d\.,]+)$/, '可用: \-$1'],
    [/^Get ([\d\.,]+)$/, '获取 $1'],
    [/^Reincarnate ([\d\.,]+) times$/, '转生 $1 次'],
    [/^Meta item ([\d\.,]+)$/, '元项 $1'],
    [/^P([\d\.,]+) Upgrade ([\d\.,]+)$/, 'P$1 升级 $2'],
    [/^Recruiting Upgrade ([\d\.,]+)$/, '招募升级 $1'],
    [/^Live until the age of ([\d\.,]+)$/, '活到 $1 岁'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^ lvl ([\d\.,]+)$/, ' 等级 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);