/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "- (Required:": "- (要求:",
    "- spending": "- 花费",
    "= net per day)": "= 每天净收入)",
    "/day": "/天",
    "Work": "工作",
    "Beggar": "乞丐",
    ") * level * charisma * job multiplier * specific multipliers": ") *等级*魅力*工作乘数*具体乘数",
    "Age:": "年龄:",
    "base revenue (": "基本收入(",
    "Basic jobs": "基础工作",
    "beta version :": "测试版:",
    "Character": "角色",
    "Current Job:": "当前工作:",
    "Cyberpunk Life": "赛博朋克生活",
    "Day:": "天数:",
    "Events": "事件",
    "Exp": "经验值",
    "Focus:": "专注:",
    "Game loaded": "游戏已加载",
    "Gym access": "健身房访问权限",
    "Hey! Come here, you may find": "嘿!到这儿来，你会发现",
    "income": "收入",
    "Income /day:": "收入/天:",
    "Income/day": "收入/天",
    "Inventory": "库存",
    "Key to the renting system": "租赁系统的关键",
    "Level": "等级",
    "level :": "等级:",
    "level max :": "最高等级:",
    "MaxLevel": "最高等级",
    "Money": "金钱",
    "Money Total:": "总计金钱:",
    "NaN": "NaN",
    "Next unlock:": "下一个解锁:",
    "NextLevel": "下一级",
    "Open / close": "打开/关闭",
    "OPTIONS": "选项",
    "PAUSE": "暂停",
    "Press delete to remove it and escape to cancel.": "按delete键删除，escape键取消",
    "Press enter or space to select a node.": "按“enter”或“空格”选择节点。",
    "Press enter or space to select an edge. You can then press delete to remove it or escape to cancel.": "按回车键或空格键选择一条边。然后，您可以按delete键删除它，或按escape键取消它。",
    "React Flow mini map": "反应流迷你地图",
    "Shop": "商店",
    "something useful...": "有用的东西…",
    "Story -": "剧情 -",
    "The game has been loaded 👌": "游戏已经加载👌",
    "XP /day:": "经验 /天:",
    "You can then use the arrow keys to move the node around.": "然后可以使用箭头键移动节点。",
    "You get orders from an app, then have to do everything asked. Faster than this if you want to keep a good rating.": "你从应用程序获得订单，然后必须完成所有要求。如果你想保持良好的评级，速度要比这个快。",
    "You wander in the streets...": "你在街上游荡……",
    "In the sterile, neon-lit corridors of the state's child-producing facility, you come into existence. Strangely, the processus of insemination took 0.8 seconds more than expected. The machinery hums, a line reporting the anomaly appears somewhere on a server log, and you are cast into the sprawling, brutalist cityscape, barely more than your ID number.": "在这个国家的生育机构里，你在无菌的、霓虹灯照亮的走廊里诞生了。奇怪的是，授精过程比预期多花了0.8秒。机器嗡嗡作响，服务器日志上某处出现了一条报告异常的行，你被扔进了杂乱无章的野兽派城市景观中，只比你的身份证号码多一点点。",
    "Released from the state’s cold embrace, you find yourself adrift in a metropolis where survival is a bitter struggle. As a beggar, the streets become your harsh tutors, teaching lessons of endurance amidst the relentless rain and flickering advertisements. Each day is a battle against hunger and despair, with progress a distant glimmer on the horizon.": "从这个国家冰冷的怀抱中解脱出来，你发现自己在一个大都市中漂泊，在那里生存是一种痛苦的挣扎。作为一个乞丐，街道成为你苛刻的导师，在无情的雨和闪烁的广告中教导你忍耐。每一天都是一场与饥饿和绝望的战斗，进步的曙光在地平线上隐约可见。",
    "Base money :": "基础金钱:",
    "Birth": "出生",
    "Condition": "条件",
    "Down and Out in Paris and London": "巴黎伦敦落魄记",
    "It's not like you have a choice": "你又没有选择的余地",
    "Money panel": "金钱面板",
    "See the balance between income and spending, and the current total of your money.": "查看收入和支出之间的余额，以及当前的资金总额。",
    "You are born": "你出生了",
    "You are poor and have no resources.": "你很穷，没有资源。",
    "You started the game": "你开始了游戏",
    "Price :": "价格 :",
    "Messages": "消息",
    "A Cog in the Machine": "机器上的一个齿轮",
    "A dilapidated abode, where pests are the landlords. It leaks when it rains, but it is home.": "破败的住所，害虫是房东。下雨时漏水，但这是家。",
    "A new item is available in the shop": "商店里有一种新产品",
    "Add a (negative) multiplier to expenses": "在费用上加一个(负)乘数",
    "Add a multiplier to skill XP": "为技能经验增加一个乘数",
    "Add a multiplier to work XP": "为工作经验增加一个乘数",
    "An outdated laptop with rusty edges, yet still capable of performing basic tasks.": "一台边缘生锈的过时笔记本电脑，但仍能执行基本任务。",
    "Base cost:": "基本费用:",
    "Capsule": "胶囊",
    "Charisma": "魅力",
    "Close All": "全部关闭",
    "Cost per day:": "每日费用:",
    "Effect:": "效果:",
    "Enhance your cognitive abilities, making you a better problem-solver and thus improving your efficiency at work.": "增强你的认知能力，使你成为一个更好的问题解决者，从而提高你的工作效率。",
    "Flat-sharing with a drug addict": "和一个瘾君子合租",
    "Focus": "专注",
    "Frugality": "节俭",
    "Gear": "装备",
    "Gear Renting System": "设备租赁系统",
    "General skills": "基本技能",
    "Get to level 4 Kitchen worker": "达到 4 级 厨房员工",
    "Get to level 50  Beggar": "达到 50 级 乞丐",
    "Home": "家",
    "Home Renting System": "房屋租赁系统",
    "Homeless": "无家可归的人",
    "Homes": "房屋",
    "In a dark kitchen, you cook a new, AI created menu every day. Strangely, that AI really pushes octopus sandwiches.": "在黑暗的厨房里，你每天都要做一份人工智能创建的新菜单。奇怪的是，这个人工智能真的推出了章鱼三明治。",
    "Is active": "已开启",
    "Life in here is hell, but you have a roof over the head.": "这里的生活是地狱，但你有个栖身之所。",
    "Master the art of making the most of resources. A crucial skill for someone who started with nothing.": "掌握充分利用资源的艺术。对于白手起家的人来说，这是一项至关重要的技能。",
    "Max : last 500 seconds": "最大：最近500秒",
    "Money chart": "金钱图表",
    "Multiply focus by:": "专注乘以:",
    "Old laptop": "旧笔记本电脑",
    "Old Motel Room": "旧汽车旅馆房间",
    "Pills subscription": "药丸订购",
    "Scratch card game": "刮刮卡游戏",
    "Shop alert": "商店提示",
    "Skill training": "技能培训",
    "Skills": "技能",
    "Slum Shack": "贫民窟的小屋",
    "Tablet": "平板电脑",
    "The ability to find inner peace boosts your capacity to learn.": "找到内心平静的能力可以提升你的学习能力。",
    "The screen is cracked and it is really old.": "屏幕裂了，而且很旧。",
    "Training:": "训练:",
    "Virus scripts": "病毒脚本",
    "With this you can see your money history in real time.": "有了这个，你可以实时看到你的钱的历史。",
    "x(multiplier) basic jobs XP": "x(乘数)基础工作经验",
    "x(multiplier) skill XP": "x(乘数)技能经验",
    "XP/day": "经验/天",
    "You can only sleep here.": "你只能睡在这里。",
    "You have your first paying job": "你有了第一份有报酬的工作",
    "You need this to be able to rent a home, or equipment. Incredible that you don't already have it.": "你需要这个才能租房子或设备。难以置信你居然还没有。",
    "You will be able to train on some skills.": "你将能够训练一些技能。",
    "You will get a scratch card game regularly.": "你会定期得到一个刮刮卡游戏。",
    "You will receive pills regularly. You have to seize the opportunity when it's here.": "你会定期收到药片。当机会来临时，你必须抓住它。",
    "Security agent by night": "夜间保安",
    "You do the same task all day.": "你整天都在做同样的工作。",
    "Reincarnate": "转生",
    "You are dead.": "你老死了。",
    "You start feeling really old.": "你开始觉得自己真的老了。",
    "You will probably be dead in a year 😱": "你可能会在一年内死去😱",
    "Click here to start a new life.": "点击这里开始新的生活。",
    "You will be 20 years old again, you will lose everything except the shop and clinic objects unlocked, and gain an important bonus : the max level in jobs and skills will be saved and will make it easier to level up.": "你将再次回到20岁，你将失去一切，除了商店和诊所对象解锁，并获得一个重要的奖励:工作和技能的最高等级将被保存，并将使其更容易升级。",
    "After seven decades of life’s virtual reality simulation, your journey ends with a standard-issue expiration notice. The state’s bureaucracy ensures that your final moments are as uneventful as a power outage. You reflect on a life of mundane compliance, your heart ceasing its beats in perfect bureaucratic rhythm. The city is of course indifferent to your departure.": "经过70年的虚拟现实模拟生活，你的旅程以一份标准的到期通知结束。国家的官僚机构确保你的最后时刻像停电一样平安无事。你反思着平凡顺从的生活，你的心脏在完美的官僚节奏中停止跳动。这座城市当然不会在意你的离去。",
    "Congratulations! You’ve landed your first paying job, working for an app that micromanages every breath you take. All day, your chip chirps instructions into your ear: walk, talk, deliver, type, repeat. Every action is timed to the second, and rated. It’s hard, sure, but at least you’re no longer dining exclusively on dumpster cuisine.": "恭喜你!你已经找到了你的第一份有偿工作，为一款微管理你每一次呼吸的应用程序工作。你的芯片整天在你耳边唧唧喳喳地发出指令:走路、说话、传递、打字、重复。每个动作都是计时到秒的，并进行评级。当然，这很难，但至少你不用再只吃垃圾桶里的菜了。",
    "(this loop:": "(当前循环:",
    ") can be used to unlock important objects in the clinic.": ")可以用来解锁诊所里的重要物品。",
    "⇾ Karma total :": "⇾业力总计:",
    "A computer glitches during an insemination. And seemingly that's all it takes, you’re reborn, carrying echoes of past skills and experiences. Nobody understands why you're obsessed with déjà vu...": "在人工授精过程中，电脑出现故障。似乎这就是一切，你重生了，带着过去的技能和经验的回声。没有人理解你为什么痴迷于 gityx.com...",
    "Clocking Out": "打卡",
    "Get to level 2 App Slave": "达到 2 级 应用程序奴隶",
    "Karma (": "业力 (",
    "Karma after transfer :": "转让后的因果报应:",
    "Karma panel": "业力面板",
    "Karma per day = ((money per day / 10) + (PI per day / 100) + NI total) / 100 000 000": "每天的业力 = ((每天的钱 / 10) + (每天的PI / 100) + NI 总数) / 100 000 000",
    "Karma this loop :": "当前循环业力:",
    "Karma:": "业力:",
    "Reboot": "重启",
    "You died": "你死了",
    "You gain karma daily, but you'll be able to use it only after a reincarnation (it will then be transfered in the total).": "你每天都会获得业力，但你只有在轮回之后才能使用它(然后它会被转移到总数中)。",
    "You have the opportunity to live your life again": "你有机会重新开始你的生活",
    "Karma.": "业力.",
    "Add a multiplier to work revenue": "增加工作收入的乘数",
    "but I already have you in the client DB...": "但我已经在客户数据库里找到你了",
    "Clinic access": "诊所访问权限",
    "It's weird, I'm sure we never met,": "很奇怪，我们肯定没见过面，",
    "Street Cred": "街头功绩",
    "The stains on the walls and carpet tell a thousand tales. Not the best, but private.": "墙上和地毯上的污迹诉说着千言万语。不是最好的，但很私密。",
    "This will allow you to enter the Clinic.": "这能让你进入诊所。",
    "Underground Bunker": "地下室",
    "You are dead. If you reincarnate now, you will get": "你已经死了。如果你现在转世，你会得到",
    "Your charisma allows you to influence others with ease, proving beneficial in work situations and increasing your revenue.": "你的魅力使你能轻松地影响他人，在工作中证明自己是有益的，并增加你的收入。",
    "Enable Autosave (will save the game every 5 seconds).": "开启自动保存(每5秒保存一次游戏)。",
    "Game changelog here": "这里是游戏更新日志",
    "Join the Discord Server:": "加入Discord服务器:",
    "Load Game": "加载游戏",
    "Reset Game (delete save!)": "重置游戏(删除存档!)",
    "Save Game": "保存游戏",
    "Body modifications": "身体修饰",
    "Buy objects with money. You will keep them after a reincarnation.": "用金钱购买物品。转生后可保留",
    "Character panel": "角色面板",
    "Choose a job and monitor your experience progress here.": "在这里选择一份工作，并监控你的经验进步。",
    "Choose a job to earn money and gather experience in that role. As you progress, you'll advance in levels.": "选择一份既能赚钱又能积累经验的工作。随着你的进步，你的等级也会提高。",
    "Do you have siblings in": "你有兄弟姐妹在",
    "Each level up increases your pay and opens up opportunities for new jobs.": "每升一级都会增加你的收入，并为你提供新的工作机会。",
    "Elevate it by renting better homes and gear.": "通过租用更好的房子和设备来提升它。",
    "Events panel": "事件面板",
    "Focus enhances your skill and job experience gain. Your current focus level is:": "专注可以提高你的技能和工作经验。你当前的专注等级:",
    "Get access to a new menu in the clinic.": "获得诊所新菜单的权限。",
    "Here in Ubik Group™ we're delighted to have you as a renter. Adjust your home and equipment depending on your revenue!": "在 阳光帝国，我们很高兴您成为我们的租客。根据你的收入调整你的家和设备!",
    "Here you can rent a home to upgrade your Focus.": "在这里，你可以租用房屋来升级你的专注。",
    "Home panel": "家面板",
    "Key details about your character are displayed here.": "关于你的角色的关键细节在这里显示。",
    "Select a skill to make it progress.": "选择一个技能，使其进步。",
    "Shop panel": "商店面板",
    "Skills have various effects like adding multipliers to jobs xp or revenue, decreasing expenses etc.": "技能有各种各样的效果，比如增加工作经验或收入的乘数，减少开支等。",
    "Skills panel": "技能面板",
    "the area or something ?": "这片区域还是什么?",
    "The learning speed depends on Focus.": "学习速度取决于专注。",
    "Work panel": "工作面板",
    "years.": "年。",
    "You begin the game at the age of": "你开始游戏的年龄是",
    "You can also equip or unequip different gear, each one has a specific effect.": "你也可以装备或不装备不同的装备，每一个都有特定的效果。",
    "You can rent for a cost superior to your revenue, if your money falls to 0 you'll be homeless again and every gear will be unequiped.": "你可以以高于收入的价格租房，如果你的钱降至0，你将再次无家可归，一切都将毫无疑问。",
    "Your expected lifespan is:": "你的预期寿命是:",
    ") to unlock important upgrades": ")来解锁重要的升级",
    "A collection of scripts used to steal money.": "用来偷钱的脚本集合。",
    "A compact, remotely-controlled drone designed for surveillance and security.": "一种小型的远程控制无人机，用于监视和安保。",
    "A repurposed fallout shelter. Cold, metallic, safe.": "一个改头换面的防空洞。冰冷，金属，安全。",
    "Add a multiplier to your Karma gains.": "在你的业力收益中增加一个乘数。",
    "Apartment in the Stacks": "书库公寓",
    "Clinic": "诊所",
    "Clinic panel": "诊所面板",
    "Criminal jobs": "犯罪的工作",
    "Get some money at the start of your life.": "在你的人生开始的时候要有一些钱。",
    "Get to level 20  Criminal consortium president": "达到20级犯罪集团会长",
    "Get to level 20  Security Company CEO": "达到20级安保公司CEO",
    "if you have enough karma to pay.": "如果你有足够的业力。",
    "In the clinic you can buy more levels for various upgrades.": "在诊所，你可以购买更多级别的各种升级。",
    "Karma multiplier": "业力乘数",
    "Level :": "等级:",
    "Level:": "等级:",
    "Life expectancy +": "预期寿命+",
    "Money at birth": "出生时的钱",
    "Price for next level:": "下一个级别的价格:",
    "Security Drone": "安保无人机",
    "Spend your karma (": "花你的业力(",
    "Stealth Suit": "隐身服",
    "Upgrade your life expectancy by 1 year.": "将你的预期寿命延长1年。",
    "We offer a large array of services": "我们提供各种各样的服务",
    "when starting a new life": "当开始新的生活",
    "x(multiplier) crime jobs XP": "x(乘数)犯罪工作经验",
    "x(multiplier) security jobs XP": "x(乘数)安保工作经验",
    "You sell fake memory cards in the streets.": "你在街上卖假存储卡。",
    "Get a fast way to end your life.": "找一个快速的方法结束你的生命。",
    "Ohh! Him again!": "哦!又是他!",
    "Sit down, my friend.": "请坐，我的朋友。",
    "Suicide tooth": "自杀之牙",
    "(Political Influence).": "(政治影响力)。",
    ") to get people ready to work for you. That will generate PI every time you click Activate.": ")让人们准备好为你工作。这将在每次点击激活时生成PI。",
    "/activation": "/激活",
    "╚═════ total :": "╚═════ 总计 :",
    "╠═ /click :": "╠═ /点击:",
    "╠═══ /day :": "╠═══ /每天:",
    "Activate": "激活",
    "Add one person in your organization. You'll need adequate real estate.": "在您的组织中添加一个人。你需要足够的地产。",
    "Available: 0": "可用:0",
    "Bio-Monitor": "生物监测器",
    "Buy": "购买",
    "Click the Activate button to use the infrastructure and get": "点击激活按钮使用基础设施并获得",
    "Converted Warehouse Loft": "改建仓库阁楼",
    "Create an organization": "创建一个组织",
    "Develop advanced training programs for security personnel, ensuring they're equipped with the latest techniques in cyber defense and physical combat.": "为安保人员制定先进的培训计划，确保他们配备最新的网络防御和物理作战技术。",
    "From infrastructure :": "基础设施方面:",
    "From projects :": "来自项目:",
    "Get to level 30 Thief": "升级到 30 级 窃贼",
    "In \"Infrastructure\", you'll spend Political Influence (": "在“基础设施”中，您将使用政治影响力(",
    "In \"Projects\", use your": "在“项目”中，使用你的",
    "Infrastructure": "基础设施",
    "Levelling up in this category will upgrade the amount of PI you get every day.": "在这一类别中升级将升级你每天获得的PI数量。",
    "Levelling up in this category will upgrade the amount of PI you get from each activation.": "在此类别中升级将升级您从每次激活中获得的PI数量。",
    "Luxury Micro-Apartment": "豪华微型公寓",
    "Manage your organization here and create Political Influence.": "在这里管理你的组织，创造政治影响力。",
    "Neuro-Stimulant": "神经兴奋剂",
    "New Power Rising": "新势力崛起",
    "Org": "组织",
    "Organization": "组织机构",
    "Organization panel": "组织委员会",
    "Paladin Protocols": "圣骑士的协议",
    "Pay in PI to build projects for your organization.": "支付PI为您的组织构建项目。",
    "Pay in PI to build the infrastructure of your organization.": "支付PI来构建组织的基础设施。",
    "Personnel :": "人员:",
    "Pills subscription II": "药丸订购II",
    "Political Influence :": "政治影响力:",
    "Political Influence:": "政治影响力:",
    "Projects": "项目",
    "Real estate": "房地产",
    "Recruiting": "招聘",
    "Security company": "安保公司",
    "Security jobs": "安保工作",
    "so you can gain more PI automatically with time.": "所以你可以随着时间自动获得更多的PI。",
    "Some people contacted you, there is now a possibility of creating an organization around your security work.": "有人联系了你，现在有可能围绕你的安保工作创建一个组织。",
    "The projects will create PI automatically.": "项目将自动创建PI。",
    "Type :": "类型:",
    "Upgrade the maximum possible number of recruits": "升级新兵的最大可能数量",
    "will be accounted to produce karma and the levels in your organization will unlock objects in the store.": "将被计算为产生因果报应，您组织中的级别将解锁商店中的对象。",
    "With ambition in your heart and a vision in your mind, you create an organization, attracting a diverse group of individuals to help you turn dreams into reality.": "有了心中的雄心壮志和心中的愿景，你创建了一个组织，吸引了形形色色的人来帮助你把梦想变成现实。",
    "You created an organization": "你创建了一个组织",
    "You created your first organization": "你创建了你的第一个组织",
    "You stay all night in a warehouse and hope nothing happens": "你整晚都待在仓库里，希望别出事",
    "You will lose everything about your organization when dead, but the store could have a way to prevent this.": "当你的组织死亡时，你将失去一切，但商店可以有办法防止这种情况发生。",
    "You will receive pills more often.": "你会更经常收到药片。",
    "Heist Mastery": "抢劫精通",
    "Underworld Connections": "黑道关系",
    "✧ Scratchcard ✧": "✧刮刮卡✧",
    "A clandestine communication system immune to surveillance, ensuring safe and encrypted conversations among members.": "一个不受监视的秘密通信系统，确保成员之间的安全加密对话。",
    "A tiny box in the towering stacks. The neon lights outside never shut off.": "高耸的书架里的一个小盒子。外面的霓虹灯从不熄灭。",
    "Add a multiplier to \"Street Cred\" XP": "增加“街头信誉”经验的乘数",
    "Add a multiplier to crime jobs revenue": "增加犯罪工作收入的乘数",
    "Add a multiplier to crime jobs XP": "增加犯罪工作经验的乘数",
    "AVAILABLE": "可用",
    "Become a seasoned criminal, adept at maximizing profits from every unlawful venture.": "成为一名经验丰富的罪犯，善于从每一次非法冒险中获利最大化。",
    "Brain Chip": "大脑芯片",
    "Crime skills": "犯罪技能",
    "Criminal gang": "犯罪团伙",
    "ElectroLoot Layers Scratchcard game": "电光层刮卡游戏",
    "Get to level 80 Security Consultant": "达到80级安全顾问",
    "Hidden weapons": "隐藏的武器",
    "Level : ★☆☆☆☆": "等级:★☆☆☆",
    "Nighthawk Network": "夜鹰网络",
    "Not for resale": "不得转售",
    "Scratchcard game": "彩票游戏",
    "Scratcher Deluxe": "刮管器豪华",
    "Some people contacted you, there is now a possibility of creating an organization around your criminal activities 🥷.": "有人联系了你，现在有可能围绕你的犯罪活动建立一个组织🥷。",
    "Spacious, raw, with a touch of industrial aesthetics. Your haven in the urban jungle.": "宽敞，原始，带有一丝工业美学。你在都市丛林中的天堂。",
    "Submission waves emittor": "提交波发射器",
    "Suicide Tooth": "自杀之牙",
    "Terminator arms": "终结者手臂",
    "The upgrade for pro scratchers!™ Wider scratches (+20%)": "升级为专业挠痒痒!™更宽的划痕(+20%)",
    "Time to next scratchcard :": "下一张刮刮卡时间:",
    "Troll farmer": "巨魔农夫",
    "You have a scratchcard ready in the shop": "你在商店里准备好了刮刮卡",
    "Your connections in the seedy underbelly of the city pay off, yielding more valuable information and resources.": "你在城市底层的关系网会得到回报，带来更多有价值的信息和资源。",
    "Your reputation on the streets can prove to be an important asset, facilitating your advancement in the world of crime.": "你在街头的名声会成为一笔重要的财富，帮助你在犯罪世界中取得进步。",
    "A poisoned tooth, used for a quick and - if you trust the seller - painless death.": "一颗有毒的牙齿，如果你相信卖家的话，可以快速无痛死亡。",
    "A wearable device that continuously monitors physiological information.": "一种持续监测生理信息的可穿戴设备。",
    "Add a multiplier to \"Security Protocols\" XP": "增加一个乘数\“安全协议\”XP",
    "Add a multiplier to security jobs revenue": "增加安保工作收入的乘数",
    "Add a multiplier to security jobs XP": "增加一个乘数到安保工作经验",
    "Advance your knowledge of defensive strategies, making you more valuable in the security field.": "提高你的防御策略知识，使你在安保领域更有价值。",
    "Advanced stealth suit, ideal for covert operations.": "先进的隐身服，非常适合秘密行动。",
    "Leto I's Suicide tooth": "莱托一世的自杀之牙",
    "Same thing as a classic reincarnation.": "和经典的轮回一样。",
    "Security skills": "安保技能",
    "Understand and exploit the intricate security systems that protect the megacorps.": "了解并利用保护巨型军团的复杂安保系统。",
    "x(multiplier) Heist Mastery skill XP": "x(乘数)抢劫精通技能经验",
    "x(multiplier) Vigilant Sentinel skill XP": "x(倍增器)警戒哨兵技能经验值",
    "You safeguard the lives of important and notorious figures of the city.": "你保护着这座城市中重要而臭名昭著的人物的生命。",
    "You steal small things to stay under the radar.": "你偷小东西是为了不被发现。",
    "Your alertness and tactical acumen turn every security gig into a gold mine.": "你的警觉性和战术敏锐性会让每一份安保工作都变成一座金矿。",
    "A next-generation quantum computer capable of hacking sophisticated systems.": "下一代量子计算机能够破解复杂的系统。",
    "A potent nootropic drug that enhances cognitive abilities.": "增强认知能力的强效益智药。",
    "Advanced eyewear that can analyze digital data and identify vulnerabilities.": "可以分析数字数据并识别漏洞的高级眼镜。",
    "Available: 1": "可用数量:1",
    "Business super AI": "商业超级AI",
    "Cybernetics Clinic Owner": "控制论诊所老板",
    "Data-Goggles": "数据护目镜",
    "Get to level 15 Security Consultant": "达到15级安全顾问",
    "Life Planner": "人生规划师",
    "Organization bank": "组织银行",
    "Penthouse in a High-rise": "高层的顶层公寓",
    "Quantum PC": "量子电脑",
    "Security Drones Swarm Specialist": "安全无人机群专家",
    "Small yet modern, with smart appliances. A perfect fusion of style and technology.": "小巧而现代，配有智能家电。时尚与科技的完美融合。",
    "Stock market super AI": "股市超级人工智能",
    "x(multiplier) business jobs XP": "x(乘数)商业工作经验",
    "x(multiplier) Data Heist Pro skill XP": "x(倍增器)数据抢劫专业技能经验",
    "x(multiplier) Focus": "x(倍增器)专注",
    "x(multiplier) hacking jobs XP": "x(乘数)黑客工作经验",
    "You get access to an exclusive AI helping on reports on market and decision-making.": "你可以访问一个独家的人工智能，帮助报告市场和决策。",
    "You'll be able to set some choices about your life.": "你将能够对你的生活做出一些选择。",
    "You'll get to keep half of the levels of your organization when reincarnated.": "当你转世时，你将保留你组织一半的等级。",
    "Retrofitted Industrial Complex": "改造工业综合体",
    "Protect corporate secrets by securing their physical and digital assets. Never a dull moment.": "通过保护公司的物理和数字资产来保护公司机密。从来都不会让人感到沉闷。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Security Protocols": "安保协议",
    "Bodyguard for Hire": "雇佣保镖",
    "Vigilant Sentinel": "警戒哨兵",
    "Security Consultant": "安全顾问",
    "Defensive Specialist": "防守专家",
    "Thief": "窃贼",
    "Scammer": "骗子",
    "Factory worker": "工厂工人",
    "Frugality": "节俭",
    "Kitchen worker": "厨房员工",
    "Relaxation": "放松",
    "Logic": "逻辑",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "App slave": "应用程序奴隶",
    "Years before next level: ": "距离下一级年数：",
    "Days before next level: ": "距离下一级天数：",
    "Beggar - ": "乞丐 - ",
    "Relaxation - ": "放松 - ",
    "Thief - ": "窃贼 - ",
    "Scammer - ": "骗子 - ",
    "Logic - ": "逻辑 - ",
    "Charisma - ": "魅力 - ",
    "Vigilant Sentinel - ": "警戒哨兵 - ",
    "Underworld Connections - ": "黑道关系 - ",
    "Street Cred - ": "街头信条 - ",
    "Factory worker - ": "工厂工人 - ",
    "Frugality - ": "节俭 - ",
    "Security Protocols - ": "安保协议 - ",
    "Bodyguard for Hire - ": "雇佣保镖 - ",
    "Security Consultant - ": "安全顾问 - ",
    "Defensive Specialist - ": "防守专家 - ",
    "Heist Mastery - ": "抢劫精通 - ",
    "Security agent by night - ": "夜间安保人员 - ",
    "Kitchen worker - ": "厨房员工 - ",
    "Heist Mastery lvl ": "抢劫精通 等级 ",
    "Factory worker lvl ": "工厂工人 等级 ",
    "Relaxation lvl ": "放松 等级 ",
    "Underworld Connections lvl ": "黑道关系 等级 ",
    "Security agent by night lvl ": "夜间安保人员 等级 ",
    "Street Cred lvl ": "街头信条 等级 ",
    "Frugality lvl ": "节俭 等级 ",
    "Security Protocols lvl ": "安保协议 等级 ",
    "Logic lvl ": "逻辑 等级 ",
    "Security Consultant lvl ": "安全顾问 等级 ",
    "Thief lvl ": "窃贼 等级 ",
    "Bodyguard for Hire lvl ": "雇佣保镖 等级 ",
    "Vigilant Sentinel lvl ": "警戒哨兵 等级 ",
    "Beggar lvl ": "乞丐 等级 ",
    "Defensive Specialist lvl ": "防守专家 等级 ",
    "Scammer lvl ": "骗子 等级 ",
    "Kitchen worker lvl ": "厨房员工 等级 ",
    "Math.max(1 - Math.log(level ": "Math.max(1 - Math.log(等级 ",
    "Multiplier: 1 + (level ": "乘数: 1 + (等级 ",
    "You died at ": "你活到了 ",
    "Slots: ": "槽位: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    " (DEAD)": " (死亡)",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^ x ([\d\.]+)$/,
    /^→ x ([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\[([\d\.,]+)\] \* ([\d\.]+)\)$/,
    /^\[([\d\.,]+)\]\) \/ ([\d\.,]+), ([\d\.]+)\)$/,
    /^ \- ([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^PI \/ click: (.+) x (.+) \(x(.+)\)$/, 'PI / 点击: $1 x$2 (x$3)'],
    [/^PI \/ day: (.+) x (.+) \(x(.+)\)$/, 'PI / 天: $1 x$2 (x$3)'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^x([\d\.]+) basic jobs XP$/, 'x$1 基础工作经验'],
    [/^x([\d\.]+) skill XP$/, 'x$1 技能经验'],
    [/^x([\d\.]+) Data Heist Pro skill XP$/, 'x$1 数据抢劫专业技能经验'],
    [/^x([\d\.]+) work XP$/, 'x$1 工作经验'],
    [/^x([\d\.]+) \"Street Cred\" XP$/, 'x$1 “街头信条”经验'],
    [/^x([\d\.]+) \"Security Protocols\" XP$/, 'x$1 “安保协议”经验'],
    [/^x([\d\.]+) Vigilant Sentinel skill XP$/, 'x$1 警戒哨兵技能经验'],
    [/^x([\d\.]+) Heist Mastery skill XP$/, 'x$1 抢劫精通技能经验'],
    [/^x([\d\.]+) business jobs XP$/, 'x$1 商业工作经验'],
    [/^x([\d\.]+) hacking jobs XP$/, 'x$1 黑客工作经验'],
    [/^x([\d\.]+) crime jobs XP$/, 'x$1 犯罪工作经验'],
    [/^x([\d\.]+) security jobs XP$/, 'x$1 安保工作经验'],
    [/^x([\d\.]+) Focus$/, 'x$1 专注'],
    [/^x([\d\.]+) expenses$/, 'x$1 支出'],
    [/^x([\d\.]+) security jobs revenue$/, 'x$1 安保工作收入'],
    [/^x([\d\.]+) crime jobs revenue$/, 'x$1 犯罪工作收入'],
    [/^x([\d\.]+) work revenue$/, 'x$1 工作收入'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) recruits in org$/, '$1 组织新人'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\+ ([\d\.,]+) years$/, '\+ $1 年'],
    [/^Hack Cluster ([\d\.,]+)$/, '黑客集群 $1'],
    [/^Get ([\d\.,]+)$/, '获取 $1'],
    [/^Reincarnate ([\d\.,]+) times$/, '转生 $1 次'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^ lvl ([\d\.,]+)$/, ' 等级 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);